### ISSUE TITLE
Search not working properly?

### ISSUE THREAD

**Issue by Mampfred** [Laverna/laverna#105]
I installed Laverna today and actually i'm testing it with a few entries.

I've got two entries which include the word "css"

![liste](https://cloud.githubusercontent.com/assets/7797895/3179107/07e31a8e-ec22-11e3-9d26-8b2c1fee76f3.JPG)

but when i search for "css" only one result is given

![css_result](https://cloud.githubusercontent.com/assets/7797895/3179116/1ddcfa8a-ec22-11e3-81d9-415fe8d6c064.JPG)

I also added another entry which includes "html" and when i searched for "html", two results were returned.

**Comment by ion-storm** [comment]
Having this same bug with Beta v0.7.4-RC1 on Windows 10, search however works, but does not search additional pages, If I click Older and make sure the results are in there the search works.

**Comment by baxter100** [comment]
Having the same problem with laverna 0.7.3 on linux. Also searching by clicking on tags in the notebooks menu doesn't work
