### ISSUE TITLE
FilterProvider syntax changed in Apache 2.4

### ISSUE THREAD

**Issue by matjam** [Laverna/laverna#110]
[Fri Jun 06 09:55:02.328815 2014] [core:alert] [pid 12299] [client x:46735] /var/www/laverna/.htaccess: FilterProvider takes three arguments, filter-name provider-name match-expression

Seems similar to this issue:

https://github.com/contao/core/issues/4552
https://github.com/contao/core/commit/0cec9eed050b788c245bacede4b4ca59830b58c2

**Comment by chaseconey** [comment]
+1. This did seem to fix it for me as well
