### ISSUE TITLE
Laverna cannot handle common mime types

### ISSUE THREAD

**Issue by aproposnix** [Laverna/laverna#113]
Currently Laverna is only able to handle image attachments. If anything else is added, the note will only show a broken image link. 

Depending on how you look at it, this is either a bug (esp., if Laverna is supposed to be an open alternative to Evernote) or an enhancement. 

Personally I take the view that this is a bug.  In order to be a viable replacement to Evernote, Laverna should be able to provide the basic functionality that's available in Evernote. 

Example - I attached an image and DOC file - the doc is broken: 
![selection_052](https://cloud.githubusercontent.com/assets/6204273/3213839/eba31e20-ef9e-11e3-9f70-910e34dc8264.png)

EDIT: This is related to issue #45 - In order to implement that one, this issue will need to be sorted out.

**Comment by isomerase** [comment]
Thanks!
