### ISSUE TITLE
Feature Request: WYSIWYG editing

### ISSUE THREAD

**Issue by aproposnix** [Laverna/laverna#120]
For non-technical users, the use of markup can be quite daunting. I've shown the app to many people and they all say the same thing:
1. Why can't I just format it in the same view?
2. The preview mode is very distracting. 
3. In 'normal mode' I cannot understand why it shows the markup and not the final output [they expect that when they use the formatting bar, they'll immediately see the formatted text]

I think it would be a great service to those who want to use opensource over proprietary software to provide this functionality. It would really broaden your audience (assuming here that you want to broaden your audience).

**Comment by claell** [comment]
I would really like it as it would allow to not need the two sides view.

**Comment by jbolila** [comment]
[MultiMakdown](http://fletcher.github.io/MultiMarkdown-5/tables.html) has support for tables.
