### ISSUE TITLE
remotestorage uses http links

### ISSUE THREAD

**Issue by carlokok** [Laverna/laverna#122]
I have a remote storage server (Restore) only listening to https. webfinger is set to https, the authentication goes fine too, then it later tries to access the same thing via http and with it, fail. How do I make it always go to https://?

**Comment by wwebfor** [comment]
I'm not sure how it can be done. I think it's the issue with RemoteStorage library itself. Can you report this issue there?

**Comment by NWuensche** [comment]
Right now I'm looking to solve the bugs for milestone 1. Could someone please close all of the ones that are already fixed, like this one?

**Comment by claell** [comment]
Isn't "third party issue" a better label than "fixed"?
