### ISSUE TITLE
Issue at setup with phantomjs

### ISSUE THREAD

**Issue by Thomas830** [Laverna/laverna#129]
Hi there ! 
Not sure it's the place but I've got a problem when doing npm install on Ubuntu 14.04 64bits. 
Here's the issue:
`Failed at the grunt-phantomcss@0.2.3 postinstall script.
This is most likely a problem with the grunt-phantomcss package,not with npm itself.`
 
Does anyone got a clue on this ?
Thanks

**Comment by wwebfor** [comment]
PhantomCSS was removed altogether.
