### ISSUE TITLE
Feature Request: Import/Export Notes in JSON

### ISSUE THREAD

**Issue by andtheWings** [Laverna/laverna#133]
Users can export notes in JSON format and import them into a different profile.

This would help resolve issue #100.

**Comment by raphael0202** [comment]
Great idea, it would allow to backup notes easily.

**Comment by xawos** [comment]
That would be GREAT! 
Choosing a format would be EXCELLENT, but i'm not in a rush.
That would be useful for bringing data all together, or for an export of many little notebooks to a singular site.

**Comment by ryanmcnz** [comment]
This would be really useful, especially in the scenario of data loss due to whatever browser or computer issues that could pop up.
A simple save/restore from a JSON file would be a really nice addition, perhaps a tab in the Settings area would be the best spot?

**Comment by Alwaysin** [comment]
This would be awesome :)

**Comment by wwwredfish** [comment]
We implemented exporting/importing data as a zip archive which contains json and markdown files in Laverna v0.7.1-RC2. Currently it is available at: http://laverna.cc/nightly/
