### ISSUE TITLE
Node Webkit

### ISSUE THREAD

**Issue by andtheWings** [Laverna/laverna#149]
Have you all thought about packaging Laverna in Node Webkit with something like this: https://github.com/jyapayne/Web2Executable.

**Comment by bnvk** [comment]
Similar to node-webkit there is also [atom-shell](https://github.com/atom/atom-shell) which is quite promising as Github's IDE "Atom" is based on it. Here is a [pretty good comparison](http://blog.soulserv.net/first-encounter-with-atom-shell/) between both environments!

**Comment by wwebfor** [comment]
We've decided to use Electron formerly known as atom-shell.

**Comment by bnvk** [comment]
@wwebfor great to hear. I'm quite excited progress was made in
this direction. I just downloaded the Electron app and tried it
out. Way to go team :)
