### ISSUE TITLE
Wishlist Request: Integration with Owncloud/Nextcloud

### ISSUE THREAD

**Issue by aproposnix** [Laverna/laverna#155]
It would be fantastic to see Laverna integrated into Owncloud as a 3rd party app. 

Related tickets:
#104
#6

**Comment by alsternerd** [comment]
That's what selfhosted stuff should support first, then the non selfhosted stuff.
Before using laverna I did never notice remotestorage at all and I just don't get on how it works, and how to use it. (There's some page claiming it would work with owncloud because it has remotestorage enabled, which seems to be false as it's not working.)

tl;dr Add OwnCloud first.

**Comment by uraza** [comment]
:thumbsup:

**Comment by FromBabylon** [comment]
I've succefully enabled remote storage with Cozy Cloud but that doesn't sync stuff across my devices so I don't really see the point. Just a backup ?

**Comment by alsternerd** [comment]
As @FromBabylon says if it where just for backup, there has to be any restore and therfore sync option included. Backing up encrypted files, while not eb able to decrypt or resync them into the laverna instance of your choice seems like an unuseful idea.

**Comment by 5TDg9** [comment]
+1

synchronization & decryption just on the endusers side... and it wouldn't matter if laverna support owncloud or dropbox or google drive, etc....

**Comment by lancelotly** [comment]
Webdav +1   
XD

**Comment by r0bbie** [comment]
Since Dropbox sync is supported, hopeful to see OwnCloud/NextCloud support in the future.

Will be keeping an eye on this and any potential future WebDAV support (#104).

**Comment by Abraxos** [comment]
NextCloud/WebDAV +1

**Comment by ET-Bent** [comment]
NextCloud/WebDAV +1

**Comment by leveled** [comment]
This would be a "killer feature" +1

**Comment by Jean28518** [comment]
+ 1

**Comment by a-riddle-fan** [comment]
+1 with Nextcloud would be Awesome!

**Comment by Mensa5000** [comment]
+1 !!!

**Comment by StygianBlues** [comment]
+1

**Comment by funilrys** [comment]
Hi there (@ulgrimar @Mensa5000 @StygianBlues  & others),

Please stop commenting and report to  https://github.com/Laverna/laverna/issues/971#issuecomment-411423965 for the state of this project.
