### ISSUE TITLE
Doesn't work with Safari

### ISSUE THREAD

**Issue by kgrossjo** [Laverna/laverna#16]
I installed Laverna on my VPS and with Firefox on OSX I see the UI and I can use it.  With Safari on OSX I see the background (white area on the left for the list of notes, grey area on the right for the currently selected note), but there is nothing in it, just the two areas.

Using Mavericks and the Safari that comes with it.

**Comment by tiptronic** [comment]
Is this project dead already?

And: it still doesn't work on Safari, OSX 10.10.2

NotFoundError: DOM IDBDatabase Exception 8: An operation failed because the requested database object could not be found.

**Comment by HLFH** [comment]
I believe this project is dead. It does not work for Safari for me too... Safari 7.1.3, OS X 10.9.5

**Comment by sheafferusa** [comment]
Thought, I too should probably add another related issue, which is: 
The App also doesn't work on the mobile version of safari, or rather Safari on the iPhone (iOS 7) & iPad (iOS 9.1-13B143/Latest Version). Both show the same thing as discussed in the issue above that is, they just show the menu & a blank white background. Nothing else. Although the menu seems to be working fine. 
One more obvious thing is, that it of course doesn't work on the Mac OSX (Mavericks)   Safari too. When using Chrome on Mac OSX, it works fantastically. 

- -I tested it on the above mentioned devices using my own copy of the latest version of the App hosted on my server as well as the App's officially deployed version in its homepage. The issue persists without a clue as to what the problem might be. 


I hope that helps. By the way, the new & improved UI is fantastic & it made me fall in love with Laverna, all over again! 
Thanks to the developers; for devoting your precious time to create something as brilliant as this. 

--Animesh

**Comment by wwwredfish** [comment]
@sheafferusa Thanks for your kind words. We are planning to release a stable version tomorrow which will probably resolve this issue with Safari.

**Comment by suchkultur** [comment]
It still does not work at least on my mobile and desktop Safari/webkit based browsers as mentioned above. I use the official version at laverna.cc . I get the `Loading` message and nothing happens for minutes. I did not check the console yet, because i thought it was a connection problem.

**Comment by wwebfor** [comment]
@suchkultur sad to hear it. It's a little hard to track down what is happening since we can't install Safari. We checked on Midori though, and it works there. We'll try to figure it out later.

**Comment by suchkultur** [comment]
@wwebfor I had the chance to check what's happening in the web console (Safari dev tools). I See:

    TypeError: undefined is not an object (evaluating 'n.createInstance')

in line 14 of `db.js` . Maybe i can help tracking this issue down?

**Comment by wwebfor** [comment]
@suchkultur it seems like it cannot find localForage on Safari for some reason.

**Comment by wwebfor** [comment]
We were able to reproduce and fix this issue with Epiphany browser. We have tested it on Safari (on Saucelabs) and everything seems to be working. If the bug still persists, we can re-open the issue.

**Comment by ota1977** [comment]
Hello, l found that laverna doesn't work on iOS 9.2.1(iphone) and OSX10.11.3/Safari 9.0.3
Laverna stay "LOADING..." screen and doesn't proceed.

OSX Safari end with
Unexpected CSS token: : core.css:5:64833
Unexpected CSS token: : core.css:5:130130
Unexpected CSS token: : core.css:5:130569
Unexpected CSS token: : core.css:5:130569
TypeError: undefined is not an object(evaluationg 'n.ceateInstance')     main.js:3489:1027

**Comment by wwebfor** [comment]
@ota1977, please try to open https://laverna.cc/nightly. We fixed this issue in this [pre-release][1].

[1]: https://github.com/Laverna/laverna/releases/tag/0.7.2-RC3

**Comment by ota1977** [comment]
Hi wwebfor, it's very good to know that this problem will be fixed soon, since I really like Laverna.
I could open https://laverna.cc/nightly with Safari on my Mac.

**Comment by sheafferusa** [comment]
@wwebfor Fantastic! Thanks a lot boss, for the wonderful work that you guys have done, and I am particularly happy that you guys finally crushed the bug/issue that had been troublesome since some time. Really, thanks a lot. It just works! Long live Open Source and Laverna, both! Cheers! 
:)


PS: A screenshot of Safari Preview:
![new](https://cloud.githubusercontent.com/assets/3124401/13709510/727ab518-e7da-11e5-8b27-c7c5dc1905fd.png)


Regards,
-Anime.sh

**Comment by wwebfor** [comment]
@ota1977, @sheafferusa thank you for checking and your kind words :)
