### ISSUE TITLE
Grunt Errors - variables.less not found

### ISSUE THREAD

**Issue by joshlemer** [Laverna/laverna#166]
Trying to build Laverna locally, but grunt fails with the following message:

    Running "clean:dist" (clean) task
    Cleaning .tmp...OK
    
    Running "string-replace:i18nextLocal" (string-replace) task
    
    Running "createDefaultTemplate" task
    
    Running "jst:compile" (jst) task
    >> Destination not written because compiled files were empty.
    
    Running "less:compile" (less) task
    >> FileError: '../bower_components/bootstrap/less/variables.less' wasn't found in app/styles/theme-default/theme-default.less on line 18, column 1:
    >> 17 // Core variables and mixins
    >> 18 @import "@{boot_dir}variables.less";
    >> 19 @import "@{boot_dir}mixins.less";
    Warning: Error compiling app/styles/main.less Use --force to continue.
    
    Aborted due to warnings.
    
    
    Execution Time (2014-08-31 20:00:17 UTC)
    loading tasks  492ms      ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 86%
    less:compile    73ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 13%
    Total 575ms

**Comment by wwwredfish** [comment]
It is probably fixed in the new version of Laverna. If the error appears again, feel free to open the issue again.
