### ISSUE TITLE
grunt build gives me Error: ENOENT, no such file or directory '[...]/laverna/app/bower_components/jquery/dist/jquery.js'

### ISSUE THREAD

**Issue by LudovicRousseau** [Laverna/laverna#176]
```
$ grunt build
Running "clean:dist" (clean) task
Cleaning .tmp...OK

Running "string-replace:i18nextLocal" (string-replace) task
File app/scripts/app.js created.

Running "createDefaultTemplate" task

Running "jst:compile" (jst) task
>> Destination not written because compiled files were empty.

Running "less:compile" (less) task
File app/styles/main.css.map created.
File app/styles/main.css created.

Running "useminPrepare:html" (useminPrepare) task
Going through app/index.html to update the config
Looking for build script HTML comment blocks

Found a block:
        <!-- build:css({.tmp,app}) styles/main.css -->
        <link rel="stylesheet" href="styles/main.css">
        <!-- endbuild -->
Updating config with the following assets:
    - {.tmp,app}/styles/main.css

Found a block:
        <!-- build:js scripts/vendor/modernizr.js -->
        <script src="bower_components/modernizr/modernizr.js"></script>
        <!-- endbuild -->
Updating config with the following assets:
    - app/bower_components/modernizr/modernizr.js

Found a block:
        <!-- build:js scripts/main.js -->
        <script data-main="scripts/main" src="bower_components/requirejs/require.js"></script>
        <!-- endbuild -->
Updating config with the following assets:
    - dist/scripts/main.js

Configuration is now:

  cssmin:
  { dist: 
   { files: 
      { '<%= yeoman.dist %>/styles/main.css': 
         [ '.tmp/styles/{,*/}*.css',
           'app/styles/{,*/}*.css' ] } },
  'dist/styles/main.css': 'dist/styles/main.css' }

  concat:
  { 'dist/styles/main.css': [ '{.tmp,app}/styles/main.css' ],
  'dist/scripts/vendor/modernizr.js': [ 'app/bower_components/modernizr/modernizr.js' ],
  'dist/scripts/main.js': [ 'dist/scripts/main.js' ] }

  uglify:
  { 'dist/scripts/vendor/modernizr.js': 'dist/scripts/vendor/modernizr.js',
  'dist/scripts/main.js': 'dist/scripts/main.js',
  'dist/bower_components/requirejs/require.js': 'app/bower_components/requirejs/require.js' }

  requirejs:
  { dist: 
   { options: 
      { baseUrl: 'app/scripts',
        mainConfigFile: 'app/scripts/main.js',
        optimize: 'none',
        exclude: [ 'dropbox', 'remotestorage' ],
        findNestedDependencies: true,
        useStrict: true,
        wrapShim: true,
        wrap: true,
        name: 'main',
        out: 'dist/scripts/main.js' } } }

Running "requirejs:dist" (requirejs) task
>> Error: Error: ENOENT, no such file or directory '/Users/rousseau/Documents/github/laverna/app/bower_components/jquery/dist/jquery.js'
>> In module tree:
>>     main
>> 
>>     at Object.fs.openSync (fs.js:438:18)
Warning: Task "requirejs:dist" failed. Use --force to continue.

Aborted due to warnings.


Execution Time (2014-09-17 21:16:58 UTC)
loading tasks   832ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 33%
less:compile     1.5s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 59%
requirejs:dist  178ms  ▇▇▇▇ 7%
Total 2.5s
```

```
$ ls app/bower_components/jquery/
AUTHORS.txt           build                 jquery.min.js
CONTRIBUTING.md       component.json        jquery.min.map
Gruntfile.js          composer.json         package.json
MIT-LICENSE.txt       jquery-migrate.js     speed
README.md             jquery-migrate.min.js src
bower.json            jquery.js             test
```
The ``app/bower_components/jquery/`` directory exists but ``app/bower_components/jquery/dist/`` do not.

I could continue the build by creating the missing ``app/bower_components/jquery/dist/`` directory and creating a symlink to ``../jquery.js`` inside it.

I guess ``grunt build``is not suposed to fail like that.

**Comment by manonthemoon42** [comment]
Anyone found a solution for that problem ?

**Comment by wwwredfish** [comment]
Fixed in the new version as we switched to Gulp. If the issue appears again, feel free to reopen it.

**Comment by Shubhangi1722** [comment]
C:\Users\SMART\AppData\Local\Programs\Python\Python35-32\tagmatic-master\grunt-t
asks\tasks>grunt --force
Running "clean:pre" (clean) task
>> 1 path cleaned.

Running "copy:pre" (copy) task
Created 23 directories, copied 74 files

Running "replace:pre" (replace) task

Running "vendor-to-vendor" task
Warning: Required path doesn't exist: C:\Users\SMART\AppData\Local\Programs\Pyth
on\Python35-32\tagmatic-master\grunt-tasks\tasks/../../lib/ Used --force, contin
uing.

Running "turnOffPotatoDeclaration:tmp" (turnOffPotatoDeclaration) task

Running "ngAnnotate:tmp" (ngAnnotate) task
>> 37 files successfully generated.

Running "turnOnPotatoDeclaration:tmp" (turnOnPotatoDeclaration) task

Running "html2js:main" (html2js) task
Successfully converted 29 html templates to js.

Running "addIncludes:templates" (addIncludes) task

Running "uglify:tmp" (uglify) task
>> 41 files created.

Running "requirejs:compile" (requirejs) task
>> Error: ENOENT: no such file or directory, open
>> 'C:\Users\SMART\AppData\Local\Programs\Python\Python35-32\tagmatic-master\lib

>> \vendor\assets\js\directives\menu-toggle.js'
>> In module tree:
>>     main
>>       config/appIncludes
Warning: RequireJS failed. Used --force, continuing.
{ [Error: Error: ENOENT: no such file or directory, open 'C:\Users\SMART\AppData
\Local\Programs\Python\Python35-32\tagmatic-master\lib\vendor\assets\js\directiv
es\menu-toggle.js'
In module tree:
    main
      config/appIncludes
]
  originalError:
   { [Error: ENOENT: no such file or directory, open 'C:\Users\SMART\AppData\Loc
al\Programs\Python\Python35-32\tagmatic-master\lib\vendor\assets\js\directives\m
enu-toggle.js']
     errno: -4058,
     code: 'ENOENT',
     syscall: 'open',
     path: 'C:\\Users\\SMART\\AppData\\Local\\Programs\\Python\\Python35-32\\tag
matic-master\\lib\\vendor\\assets\\js\\directives\\menu-toggle.js',
     fileName: 'C:/Users/SMART/AppData/Local/Programs/Python/Python35-32/tagmati
c-master/tmp/config/../../lib/vendor/assets/js/directives/menu-toggle.js',
     moduleTree: [ 'config/appIncludes', 'main' ] } }

hello this is the error that i get when i try to use grunt command to build a script. Please Help. what was your solution
