### ISSUE TITLE
Minor Bug: Cursor moves after first auto-save.

### ISSUE THREAD

**Issue by andtheWings** [Laverna/laverna#178]
After the first auto-save event when I make a new note, the cursor hops from the main text field up into the title field. Often, I don't notice this has happened and will continue typing without realizing the cursor has moved:

![fuzzy bear](https://cloud.githubusercontent.com/assets/5892089/4329481/5464d426-3f9a-11e4-8688-8fc48cf22355.jpg)

Could someone verify whether this is happening to them too?

**Comment by wwebfor** [comment]
I believe this bug was resolved.
