### ISSUE TITLE
Misplaced cursor

### ISSUE THREAD

**Issue by essicolo** [Laverna/laverna#179]
Using Firefox 32.0, Fedora 20. In Edit mode, the cursor is misplaced.
![capture d ecran de 2014-09-18 23 38 23](https://cloud.githubusercontent.com/assets/5118227/4330402/c9ab20a0-3fae-11e4-8bab-c0bc44e2ff57.png)

**Comment by wwebfor** [comment]
Does it still happen in the new version?

**Comment by essicolo** [comment]
No, it does not happen!
