### ISSUE TITLE
Dropbox authorization fails

### ISSUE THREAD

**Issue by marianoju** [Laverna/laverna#180]
After the message 

> Now you will be redirected to Dropbox authorization page. 
> Please click OK button.

![dropbox authorization](https://cloud.githubusercontent.com/assets/6254428/4335441/695834ce-3ffc-11e4-8256-78fa05ed53c3.png)

I receive an error message: 

> Error (400)
> It seems the app you were using submitted a bad request.
> If you would like to report this error to the app's
> developer, include the information below.
> 
> More details for developers
> 
> Invalid redirect_uri: u'https://laverna.cc/dropbox.html'.
> It must exactly match one of the redirect URIs you've pre-
> configured for your app (including the path)

![dropbox_-_400_-_2014-09-19_14 53 03](https://cloud.githubusercontent.com/assets/6254428/4335413/17f1ba06-3ffc-11e4-96f8-e8f66168dc66.png)

**Comment by alsternerd** [comment]
I'am stuck on the same failure as @marianoju when copying the salt, password, length etc. pp. into another laverna instance.
I synced everything encrypted with dropbox (sadly enough that it's not my owncloud) and wanted to decrypt all notes when synced on another brother.

**Comment by matthewcanty** [comment]
I hope that there will be an update to make this clearer in the app. 

I've also noticed the discrepancy of DropBox's *App Key* being called *Dropbox API key* in Laverna.

It's nice that it only took about 20 minutes to get set up with DropBox, but it should only be a few minutes!

**Comment by coworkingon-es** [comment]
Hi,
I have a problem: I've added the links and everything perfectly, but now I can't enter my account because the "login" button from dropbox doesn't "activate". It is like it is detecting the fields:

![seleccion_396](https://cloud.githubusercontent.com/assets/6212799/13346044/ca7980f0-dc63-11e5-8aa2-731a1517e714.png)

Any clue?

**Comment by wwebfor** [comment]
Hi @coworkingon-es,

If it happens on the desktop version, then that bug  was fixed in [0.7.2-RC][1]

[1]: https://github.com/Laverna/laverna/releases/tag/0.7.2-RC3
