### ISSUE TITLE
Copy/Select Text From Notes

### ISSUE THREAD

**Issue by austinbutler** [Laverna/laverna#181]
I was about to move a bunch of notes into this until I realized I couldn't copy text unless in edit mode.

**Comment by dgoodwin** [comment]
I think I'm experiencing this on Firefox as well. 40.0.3 on Fedora Linux. I experience it on my version running in sandstorm.io as well as at laverna.cc. Hitting it with Chrome as well.

**Comment by wwebfor** [comment]
The issue was solved.
