### ISSUE TITLE
Problem with Fluidapp

### ISSUE THREAD

**Issue by gsportelli** [Laverna/laverna#188]
I want to use Laverna from the status bar in OSX, but it does not work with Fluid. When I setup the Encryption, it shows the password page but nothing happens when I click on the submit button. Looking at the javascript monitor I can read this error:

[Error] TypeError: 'undefined' is not an object (evaluating 'd[c].apply')
	(anonymous function) (d9e4bb44.main.js, line 11)
	forEach (d9e4bb44.main.js, line 4)
	initialize (d9e4bb44.main.js, line 11)
	encryptInit (d9e4bb44.main.js, line 11)
	checkPasswords (d9e4bb44.main.js, line 11)
	k (d9e4bb44.main.js, line 4)
	trigger (d9e4bb44.main.js, line 4)
	checkPasswords (d9e4bb44.main.js, line 11)
	(anonymous function)
	dispatch (d9e4bb44.main.js, line 2)
	handle (d9e4bb44.main.js, line 2)

**Comment by wwebfor** [comment]
It was related to Webkit based browsers. I think we fixed this issue. If you disagree, please let us know.
