### ISSUE TITLE
markdown table issues

### ISSUE THREAD

**Issue by fabrepe** [Laverna/laverna#190]
Hi,
I have two issues concerning table. Maybe they are just misunderstood. Considering the following table:

|   | r | t |
|---|---|---|
| f | f | s |
| g | f |   |

-  the first column is hidden
- there is no border and the inner margin seems to be almost null

Is there a way to avoid both behavior ?

**Comment by wwebfor** [comment]
I just checked this and it seems like it was fixed. Can you confirm it?

**Comment by wwebfor** [comment]
Closing the issue because I think it was fixed. If you disagree, please let us know.

**Comment by fabrepe** [comment]
Sorry for the delay. I confirm it has been fixed.

**Comment by wwebfor** [comment]
No problem :)
