### ISSUE TITLE
I lost a note after editing.

### ISSUE THREAD

**Issue by vejobuj** [Laverna/laverna#192]
I can not see or edit a note. After edited the note entitled: "How to use tags and tasks". I had added tags, an image, a link, a numbered list, titles, everything that could put as formatting.
Tell me what are the necessary information you need :)

Laverna is installed from source and branch master, it dates from around 20 days

Here are some screenshots to see what I mean. Taked from Chrome 38
http://i.imgur.com/B6sd8OZ.png
http://i.imgur.com/3bhtJA4.png

I think I understand why. This is because I edited below the references links of images and links.

**Comment by wwebfor** [comment]
I think this issue was fixed. Can you confirm it so we could close it?

**Comment by wwebfor** [comment]
I think the issue was fixed. If you disagree, feel free to re-open it :)
