### ISSUE TITLE
Running Local with Chrome but cannot create a note.

### ISSUE THREAD

**Issue by brian-the-bungler** [Laverna/laverna#193]
Great app.  Just wanted to run it locally.  Here is what i did.

Downloaded zip.  Unzipped and opened index.html in chrome.  Created two new notebooks.  Cannot create a note (via red note button).  index#notes/add.  What am i missing?  Thanks,

Brian

**Comment by wwebfor** [comment]
We have recently fixed this bug in 0.7.3-RC3. Can you confirm it?

**Comment by wwebfor** [comment]
It seems to be working. If it's not the case, feel free to re-open the issue.
