### ISSUE TITLE
installation on centos 6 got failed

### ISSUE THREAD

**Issue by bentech4u** [Laverna/laverna#200]
installation on centos got failed with below error

http://pastebin.com/JbgQ1L08

i was following this tutorial : http://freedif.org/opensource-alternative-to-evernote-for-your-server-laverna/

please help me to solve this issue

**Comment by ponychicken** [comment]
You should report that bug upstream at https://github.com/imagemin/imagemin

**Comment by wwebfor** [comment]
Probably this issue can be closed since `grunt-imagemin` was causing this problem. We don't use `imagemin` anymore. If the issue persists, we can re-open it again.
