### ISSUE TITLE
is it possible to secure laverna with username and password.?

### ISSUE THREAD

**Issue by bentech4u** [Laverna/laverna#202]
i have installed laverna on my centos vps.

is it possible to secure laverna with username and password.?

thanks & Regards,
Ben

**Comment by JamborJan** [comment]
To securely use laverna and wrap it in a user role model a sandstorm package would be the right way to go. See https://github.com/sandstorm-io/sandstorm.

I'm currently looking into porting another app (paperwork, see https://github.com/twostairs/paperwork) I can put that one on my todo list as it should be not that difficult to package according to this guide: https://github.com/sandstorm-io/sandstorm/wiki/Pure-client-apps

If you want to experience how easy app deployment for developers and access / maintanece for users  with sandstorm is check out their demo here: https://demo.sandstorm.io/

(FYI @paulproteus)

**Comment by rawray7** [comment]
+1 for laverna on sandstorm
