### ISSUE TITLE
Cannot upload images

### ISSUE THREAD

**Issue by kford** [Laverna/laverna#203]
When I attempt to upload an image from my pc, this is what is added to the editor

![My Image][1]
  [1]: #c283db7c-57a0-a3d3-1c2e-a95c7c645c06

And this is what I see in my note (preview)
    <-- My browser's icon for Broken Image is here
https://laverna.cc/420debbe-f7f2-4bae-bcd4-c43e0d1db9f7” alt=”My Image” title=”” />

**Comment by axllent** [comment]
Actually the images are uploaded OK, the issue is that they are not being rendered correctly in Firefox. Chrome seems to work fine, linkking the image like:

```
<p>
<img src="blob:https%3A//laverna.cc/f247ce71-8aae-4e72-8d00-4eba7e60d96d" alt="Smoothies" title="">
</p>
```

However Firefox creates this:
```
<p>
<img src="blob:<a href=" https:="" laverna.cc="" 57deaa7a-6f15-4ca7-bba2-c90146509cbe"="">https://laverna.cc/57deaa7a-6f15-4ca7-bba2-c90146509cbe” alt=”Smoothies” title=”” /&gt;
</p>
```

**Comment by alexsourcerer** [comment]
Hi, 
Looks like I got the same issue. Following exactly the same steps in Firefox and Chromium, the picture could be seen in Chromium but not in Firefox.
The picture in Firefox is replaced by a "broken picture" icon.

**Comment by jniggemann** [comment]
I can confirm this issue with FF 35.0.1 on Win7 64bit

**Comment by Alwaysin** [comment]
I can confirm it on Firefox 36.0.1 on Win 8.1 x64. Any news on this?

**Comment by alexsourcerer** [comment]
Re-confirmed with Qupzilla 1.8.6 with webkit version 537.21
