### ISSUE TITLE
Math is partially rendered in the editor

### ISSUE THREAD

**Issue by pwelke** [Laverna/laverna#212]
I started using Laverna for organizing notes that contain a lot of Latex-formatted math. 
Sometimes, while editing, the math gets rendered in both, the editing and the preview window.

**Comment by Shchvova** [comment]
![screen shot 2015-04-26 at 10 15 15 pm](https://cloud.githubusercontent.com/assets/130387/7342030/ea1ec070-ec61-11e4-87d3-15dd7fb427de.png)

**Comment by cben** [comment]
working on patch.  Can I just constrain MathJax to the preview, or can math appear elsewhere in Laverna (e.g. list of notebook titles)?

**Comment by cben** [comment]
Ah, saw your patch (commented on #239) so not working one.
