### ISSUE TITLE
Tags and Tasks

### ISSUE THREAD

**Issue by IGitSylvia** [Laverna/laverna#215]
Hi,

I am currently testing your application, but I am having issues understanding how to use the tags in your application.

Does your app handle tasks/to dos/reminders at all? 

Do tags need to be generated first under https://laverna.cc/index.html#/notebooks?

If so then how can reference them in a note? A special hash tag?

Is there a way to generate them from a new note? 

Is there a tag cloud setting missing from your online demo? How about a linked tag with the number of notes in that tag, i.e. "Math Class Notes (18)" ?

**Comment by SouzaRM** [comment]
+1

**Comment by anselmdk** [comment]
It seems todos can be created like this:

[ ] my todo - seems to work pretty neat - I'm not sure how tags work though, would also love to find out.

**Comment by anselmdk** [comment]
Now I figured out how to write tags (in the new version): `#mytag`

**Comment by yusiwen** [comment]
@anselmdk 
How to do that? I'm new to laverna, I've add `#mytag` to title and body, neither does add any tags.

**Comment by anselmdk** [comment]
@yusiwen sorry, I haven't used the system since, so I simply can't remember...

**Comment by yusiwen** [comment]
@anselmdk That's alright, I'll study it further. Thanks anyway.
