### ISSUE TITLE
Forgot encryption password, what now?

### ISSUE THREAD

**Issue by sebie** [Laverna/laverna#218]
The title explains my issue fairly well, I forgot my password what can I do?

I do not have any notes, so it is ok. I was mostly just messing around with it.

Should I just refresh my cache?

**Comment by wwebfor** [comment]
Hi, yes you can just refresh your browser's cache. Also don't forget to clear localStorage. It can be done by clearing cookies or by opening Developer Tools and executing a command ``localStorage.clear()``.

**Comment by sebie** [comment]
Thank you! The local storage clear command didn't work, but I found a good answer on StackExchange. [Link](https://superuser.com/a/655198/378780).


Also, whilst you replied, when it says it synchronizes through multiple devices you still have to signin through 5apps right?

**Comment by sebie** [comment]
Bump?

It doesn't sync through 5apps :/

**Comment by Poorchop** [comment]
I'm using 5apps for my syncing service and it works for me without any issues. Are you entering "username@5apps.com" in the little 5apps popup in Laverna? Bear in mind that the initial sync might take a little bit of time - this is what happened in my experience at least. Also make sure your firewall is blocking the outgoing connection to 5apps.

**Comment by sebie** [comment]
All of the above I have done. And it still doesn't work.

**Comment by Poorchop** [comment]
Are you using NoScript and blocking 5apps.com? The issue is mostly likely not with Laverna since no one else seems to be having any trouble with it. It has to be your firewall or something else that's blocking access. What OS are you using on the server where you are hosting Laverna?

**Comment by sebie** [comment]
To answer your questions.

-----

> Are you using NoScript and blocking 5apps.com?

Nope.

> It has to be your firewall or something else that's blocking access.

Wierd that no one else had to change their firewall settings.. I am using a personal machine.

>What OS are you using on the server where you are hosting Laverna?

For now I am using the example, [laverna.cc](https://laverna.cc)

**Comment by sebie** [comment]
Sorry to say; I would love to have used Laverna, but as I did not get this resolved I will just close it.
