### ISSUE TITLE
We are Going to be Back

### ISSUE THREAD

**Issue by wwebfor** [Laverna/laverna#220]
Hi, all users of Laverna project. First of all thank that you are using it. We are very pleased to see that other people are also interested and use it besides of ourselves :). Currently we are not able to focus on the project but do not worry we are going to be back after a month or two.

After we return, first we are planning to do the following things:

1. Fix bugs and refactor the code;
2. Release a desktop app. It will allow you to use whatever synchronizing service you prefer to use;
3. Release a mobile app;
4. Write decent Wikis and FAQ;
5. Implement collaboration;
6. Simplify installation process;
7. [Relicense the app][1].

As of now, please keep posting issues with bugs and suggestions. We can't wait to be back :)

[1]: https://github.com/Laverna/laverna/issues/194

**Comment by pguth** [comment]
Great, love to hear that. Welcome back!

**Comment by JulR43** [comment]
Great news. I've knowledges on WebApps, particularly on Firefox OS and i'd happy to contribute ^_^.

**Comment by MegaLeon** [comment]
Great to hear. I have just discovered this product and I would love to integrate it in my workflow with those new features

**Comment by jjg** [comment]
Awesome.  I was just starting to like Laverna so I'd hate to see it stall out :)

**Comment by pguth** [comment]
Remember to show some love: [Support Laverna](https://github.com/Laverna/laverna#tips)!
