### ISSUE TITLE
no 'add' functionality in chrome. 

### ISSUE THREAD

**Issue by calenwalshe** [Laverna/laverna#222]
Cloned prebuilt laverna and tested in Chrome 40.0.2214.93 (64-bit) and received no response from the 'add' button. Tested in Firefox and the app seems fully functional. OSX 10.9.5.

**Comment by wwwredfish** [comment]
I tested on Chromium 47.0.2526.73 (64-bit) and it works. If you are still encountering the problem, feel free to reopen the issue.
