### ISSUE TITLE
Title bar size doesn't not fit well on smartphone

### ISSUE THREAD

**Issue by romu70** [Laverna/laverna#243]
Hi,
I'm trying to use Laverna on a smartphone which has  540*960 display size. In portrait mode, the Laverna title bar does not fit well the screen width: the "refresh" and "new note" buttons are located on a second line (instead of being on the first line as the notebook selector and search button) which overlaps the first note.

**Comment by romu70** [comment]
I'm not really aware of less, but I reducing the margin-right value in sidebar.less for the object ```.navbar .addlink``` from 15 px to 10 px helps a bit.

**Comment by romu70** [comment]
Indeed this didn't change anything in my case. Problem is still there.

**Comment by wwwredfish** [comment]
The changes are made on dev branch.

**Comment by romu70** [comment]
Ok thanks. An ETA?

**Comment by wwwredfish** [comment]
After we fix/re-implement synchronization.
