### ISSUE TITLE
Can't install on Ubuntu 14.04

### ISSUE THREAD

**Issue by romu70** [Laverna/laverna#244]
I'm currently trying to create a new Docker image for Laverna, and I'm facing an issue with the command:
``` npm install && bower install ```

This command ends with the following error:
> npm http 304 https://registry.npmjs.org/xtend
> npm http GET https://registry.npmjs.org/is-property
> npm http 304 https://registry.npmjs.org/is-property
> grunt-phantomcss@0.2.3 postinstall /laverna/node_modules/grunt-phantomcss
> node ./node_modules/bower/bin/bower install
> sh: 1: node: not found
> npm WARN This failure might be due to the use of legacy binary "node"
> npm WARN For further explanations, please read
> /usr/share/doc/nodejs/README.Debian
 
> npm ERR! 
> npm ERR! Additional logging details can be found in:
> npm ERR!     /laverna/npm-debug.log
> npm ERR! not ok code 0

The ``` npm-debug.log ``` file contains:

> 31796 verbose parsed url   href: '0.0.1' }
> 31797 verbose addNamed [ 'concat-map', '0.0.1' ]
> 31798 verbose addNamed [ '0.0.1', '0.0.1' ]
> 31799 silly lockFile 76b37408-concat-map-0-0-1 concat-map@0.0.1
> 31800 verbose lock concat-map@0.0.1 /root/.npm/76b37408-concat-map-0-0-1.lock
> 31801 error Error: ENOENT, open '/root/tmp/npm-31-tYQXEAeC/1429645159726-0.46182310907170177/package/lib/compiler.js'
> 31802 error If you need help, you may report this log at:
> 31802 error     <http://github.com/isaacs/npm/issues>
> 31802 error or email it to:
> 31802 error     <npm-@googlegroups.com>
> 31803 error System Linux 3.19.3-200.fc21.x86_64
> 31804 error command "/usr/bin/nodejs" "/usr/bin/npm" "install"
> 31805 error cwd /laverna
> 31806 error node -v v0.10.25
> 31807 error npm -v 1.3.10
> 31808 error path /root/tmp/npm-31-tYQXEAeC/1429645159726-0.46182310907170177/package/lib/compiler.js
> 31809 error code ENOENT
> 31810 error errno 34
> 31811 verbose exit [ 34, true ]

Any idea?

**Comment by wwebfor** [comment]
It used to be an issue with PhantomCSS. We removed it completely from Node dependency. I hope it resolved this issue. If you still encounter errors, the issue can be opened again.
