### ISSUE TITLE
`ReferenceError: shimIndexedDB is not defined` when running current master build

### ISSUE THREAD

**Issue by skddc** [Laverna/laverna#246]
Hi,

I just wanted to try to update remoteStorage.js to the latest version (0.11.2 as opposed to 0.10.0-beta, which is currently in use), and ran into the following exception after building master and running the app from `dist` on localhost:

![screenshot from 2015-04-29 20-25-10](https://cloud.githubusercontent.com/assets/842/7398227/10706032-eeae-11e4-8aaf-22cd34ce4041.png)

It only shows an endless spinner and that exception. Looks like a dependency isn't defined or built somewhere.

I haven't found out how to run the app from source before building. Maybe sth to put in the README.

**Comment by wwwredfish** [comment]
We are working on it in the dev branch.

**Comment by skddc** [comment]
Ok, switched to that. But also just seeing a spinner and more errors (but different ones):

![screenshot from 2015-04-29 20-52-27](https://cloud.githubusercontent.com/assets/842/7398802/ba1973dc-eeb1-11e4-880b-bab9e1c0c410.png)

**Comment by varod** [comment]
i get the same issue on master and tag 0.6.2 without remoteStorage. it seems the problem is browser related on my side because on firefox 40.0.3 (ubuntu) I get this error message. But if I am using Chromium 44.0.2403.89 initialization is ok and i can use laverna correctly.

**Comment by varod** [comment]
if it can help i have not the issue using 0.6.1

**Comment by varod** [comment]
another information if i run : 
```
grunt serve
```
i have not this issue but if it is behind apache I have the message "shimIndexedDB is not defined" maybe something in the conf ... any idea ?

**Comment by wwebfor** [comment]
The issue was with Requirejs configs. IndexedDBShim location was provided incorrectly.
