### ISSUE TITLE
Unstarring does not remove item from list

### ISSUE THREAD

**Issue by pguth** [Laverna/laverna#248]
Select `Favorites` -> Unstar entries -> select `Favorites` from the menu again. List does not change, items that are no longer starred show up.

The view should somehow clean up or provide an option to do that. Maybe move to the bottom half grey and/or offer something like the `Clear ...` button here: http://localtodos.com/ when cleaning up old todos.

**Comment by wwebfor** [comment]
It was already resolved in dev branch.
