### ISSUE TITLE
Performance props w/ launch screen

### ISSUE THREAD

**Issue by pguth** [Laverna/laverna#249]
I now use a recent Intel M processor (M-5Y10, 2x 800MHz • RAM: 8GB) which is quite nice overall but not suited for more intense tasks. The loading animation (cycling through shades of green) of Laverna is already a bit to heavy for my machine. Maybe we could keep that more simple or somehow watch the framerate and gracefully degrade if need be.

**Comment by pguth** [comment]
Using this loading animation on a recent Intel Core M does *not* work. I have a `asus-zenbook-ux305fa` featuring a `Intel Core M-5Y10, 2x 800MHz` and starting up Laverna when running on battery feels like mining bitcoin without ever finding a coin - it's just not usable.

**Comment by wwebfor** [comment]
We disabled animation on load altogether. I hope we can safely close this issue.
