### ISSUE TITLE
Extracting the editor standalone

### ISSUE THREAD

**Issue by newtonianb** [Laverna/laverna#251]
Is there an easy way to extract just the editor from Laverna to work on its own without the containing interface? I would appreciate some of the architects/experts feedback on potential issues.

**Comment by wwebfor** [comment]
It should not be a problem because Laverna uses [Pagedown-Ace editor][1]. If you need just an editor, then you should Pagedown-Ace.

[1]: https://github.com/benweet/pagedown-ace

**Comment by newtonianb** [comment]
@wwebfor thank you!
