### ISSUE TITLE
Table not fit to the content

### ISSUE THREAD

**Issue by MangelMaxime** [Laverna/laverna#253]
When we create a table, it's actual fit the width of the parent which is pretty ugly.

![No fitting content](http://img.prntscr.com/img?url=http://i.imgur.com/16u2EXu.png)

I have find the solution to make it fit the longer cell like that : 

![Fitting content](http://img.prntscr.com/img?url=http://i.imgur.com/JWmtCUQ.png)

The problem is I can't find where to place the css. Here are little changes to made :

```
.table {
    /* width: 100%; */ /* old line */
    width: auto;
}

.table>thead>tr>td.active, .table>tbody>tr>td.active, .table>tfoot>tr>td.active, .table>thead>tr>th.active, .table>tbody>tr>th.active, .table>tfoot>tr>th.active, .table>thead>tr.active>td, .table>tbody>tr.active>td, .table>tfoot>tr.active>td, .table>thead>tr.active>th, .table>tbody>tr.active>th, .table>tfoot>tr.active>th {
    white-space: nowrap; /* not present before */
}
```

**Comment by wwebfor** [comment]
We fixed table styles in 0.7.3-RC3. Do you agree that the issue can be closed?

**Comment by MangelMaxime** [comment]
I don't have the  code of my project anymore sorry...

**Comment by wwebfor** [comment]
OK.
