### ISSUE TITLE
RemoteStorage synching doesn't seems to work properly

### ISSUE THREAD

**Issue by gdetrez** [Laverna/laverna#255]
The synching button spins for a very long time but new notes don't get synched between browsers.

**Comment by gdetrez** [comment]
Hum, I find this in the console each time I try synching:

```json
{
  "error": {
    "code": 0,
    "message": "invalid data type: number",
    "dataPath": "/notebookId",
    "schemaPath": "/properties/notebookId/type",
    "subErrors": null
  },
  "missing": [],
  "valid": false
}
```

**Comment by Alwaysin** [comment]
I've got the same - notebooks not synchronizing. But the notes are.

The endless spinning button is a known problem from what I've read here, but it hasn't prevented me from syncing even though it is indeed spinning undefinetly sometimes.

Have you tried a CTRL+F5? It's what I had to do to see my notes the first time.

**Comment by gdetrez** [comment]
Thanks for the help @Alwaysin. That sounds like a different problem though: my notes don't synchronise either.

> Have you tried a CTRL+F5? It's what I had to do to see my notes the first time.

I'm not sure what CTRL+F5 is supposed to do but it doesn't seem to help in my case

**Comment by skddc** [comment]
Hi,

remoteStorage.js core here. My guess would be that the ID format changed from a string to a number in Laverna, yet the remoteStorage module wasn't updated to reflect the change. The module is validating against the schema of that type, so if you try to save a number on sth that's defined as having to be a string, this error would appear.

There are a couple of RS issues open in this repo, and the library version was very outdated when I checked last time. I also tried to update it myself, but I couldn't get Laverna to run locally and I didn't get help to fix that when I opened issues about it. :(

**Comment by wwebfor** [comment]
Hi @skddc, sorry if it felt like we were ignoring your issue. We are currently working on the core of app and we do not have enough time to answer all issues yet. 
We finished refactoring the core and after several days we'll start refactoring&updating sync modules and then we'll fix bugs. You are right about changing ID format. We actually did change ID format.

**Comment by skddc** [comment]
> We finished refactoring the core and after several days we'll start refactoring&updating sync modules and then we'll fix bugs.

Sounds great! Looking forward to testing it. Thanks for the update.

> You are right about changing ID format. We actually did change ID format.

So aside from fixing the code, we solved this bug then. :)

FYI: We don't have any helpers for migrating formats and existing data yet (but we're working on it), so it would be easiest (and most bulletproof) to convert between numbers and strings in the RS module and keep the current schema for now.

**Comment by wwebfor** [comment]
> would be easiest (and most bulletproof) to convert between numbers and strings in the RS module and keep the current schema for now.
Thanks for the hint. We'll do exactly that.

**Comment by bnjbvr** [comment]
Hi there, I'd really love to use Laverna with RemoteStorage! The editor looks really awesome. Is there an ETA for this bug, or some easy tasks I could do to help?

**Comment by wwwredfish** [comment]
Can someone check if the issue is solved?

**Comment by skddc** [comment]
Works for me.

@gdetrez Could you verify that it's fixed for you as well?

**Comment by gdetrez** [comment]
It looks like the notes are syncing correctly but not the notebooks...

**Comment by wwwredfish** [comment]
I see. Could you please tell us what sort of problems are you having? Are they not being added/removed/updated? And your browser and version if you can.

**Comment by gdetrez** [comment]
To try the synchronization, I opened laverna on Firefox (version 42.0) and chrome (Version 46.0.2490.86). I can see all my notes in both browsers but in Firefox, I can see none of my old notebook (but they are there in chrome).
Note that newly created notebook (either in Firefox or Chrome) get synced properly.

**Comment by claell** [comment]
What do you mean with old notebook? Notebooks you created in Chrome before setting up sync in Firefox?

**Comment by gdetrez** [comment]
Yes

**Comment by andtheWings** [comment]
Hi, they told on the remotestorage site that the module for Laverna was updated. Unfortunately, I'm still getting a looped error message: https://gist.github.com/andtheWings/93c415c1345b2f7914cf

Will keep syncing with Dropbox + encryption.

**Comment by wwwredfish** [comment]
@andtheWings thanks for uploading the gist. It made it easier for us figure out what was causing the problem.

**Comment by andtheWings** [comment]
Sync with RemoteStorage is working like a charm now.

**Comment by wwebfor** [comment]
Thanks for checking it.

**Comment by wwebfor** [comment]
@gdetrez old notebooks were not synchronized because they used to have different IDs. You have to migrate them by opening [migrate.html][1].

[1]: https://laverna.cc/migrate.html

**Comment by skddc** [comment]
Looks like that link is 404.

**Comment by claell** [comment]
Should be https://laverna.cc/nightly/migrate.html

**Comment by wwebfor** [comment]
You're right. The right link is https://laverna.cc/nightly/migrate.html. Update in the previous comment too.

**Comment by bnjbvr** [comment]
Just played a bit with it and it seems that note / notebook syncing works for me. Great job, guys! Cheers!

**Comment by wwwredfish** [comment]
We are planning to release a stable version tomorrow.

**Comment by wwebfor** [comment]
@bnjbvr we have released a new version.

**Comment by bnjbvr** [comment]
Fantastic, you guys are my today's heroes. I am gonna advertise Laverna a bit today ;-)

**Comment by wwebfor** [comment]
Thanks ;-)

**Comment by wwebfor** [comment]
Alright, seems like the issue can be closed. If it's not the case, feel free to re-open.
