### ISSUE TITLE
Server deployment 

### ISSUE THREAD

**Issue by rosoft2001** [Laverna/laverna#257]
The second time today I'm checking a project that require me to install things to server (composer, gulp, bower, npm) and I don't understand why.

If this would be a development machine I may understand (not really) but on the server should be only the files required at runtime. I just want to get the project and run it, like wordpress works. I can be bother with other stuff if I want to make a change to source. I don't, at least not in the production server.

It's anyway I can do this?

If not why?

**Comment by wwebfor** [comment]
You don't have to install all those things. You can just donwload this [ZIP archive](https://github.com/Laverna/static-laverna/archive/gh-pages.zip), unpack it to public directory of your server, and that's all.

**Comment by rosoft2001** [comment]
Thanks, that works (with some .htaccess comments). 

Now I need to see how I can sync it with Dropbox? I can read, but I don't know where is the user documentation.

**Comment by Poorchop** [comment]
Open settings, make sure you are on the "Basic" settings tab, and on the "Cloud storage" dropdown, select Dropbox. You will then see a field immediately below for a Dropbox API key. If you don't know how to obtain your API key, click on the question mark under the "Dropbox API key" text and you will see instructions for setting this up.

Most the documentation that you need is in the README. One of the developers said in another issue that they are working on proper documentation, so I'm guessing that will be available soon as well.

**Comment by api984** [comment]
So once you install it on the server, you forgot that you need to protect and limit access to /laverna/ once installed. Because its available on the internet with free4all access.
