### ISSUE TITLE
Math is rendering in the editor pane

### ISSUE THREAD

**Issue by dougcoates** [Laverna/laverna#259]
Math inbetween single and double dolar signs is being rendered in the editor pane. This makes it very difficult to edit an equaion after writing it. This issue is not straight forward to recreate as it seems to just happen every now and again, however this still makes it quite difficult to keep notes with a lot of maths.

**Comment by claell** [comment]
Is it really a duplicate? At least I think the original issue is closed.

**Comment by wwebfor** [comment]
Yes, it is a duplicate. There were several issues describing the same problem.

**Comment by claell** [comment]
Ah, now I understand. Thought you closed it because it is a duplicate.
