### ISSUE TITLE
Can't build release 0.6.2

### ISSUE THREAD

**Issue by RyanWhite04** [Laverna/laverna#265]
I can build the master branch fine, but I want to run a stable version, so i'm checking out 0.6.2
I run the following
<code>
git clone https://github.com/Laverna/laverna.git
cd laverna
git checkout tags/0.6.2
npm install -g bower grunt grunt-cli
npm install 
</code>

and get the following error messages

<code>
npm WARN package.json laverna@0.6.2 No license field.
npm WARN package.json Dependency 'phantomcss' exists in both dependencies and devDependencies, using 'phantomcss@~0.5.0' from dependencies
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.11.3
npm ERR! code ETARGET
</code>
<code>
npm ERR! notarget No compatible version found: bower-config@'>=0.2.0 <0.3.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.1.0-rc.1","0.1.0-rc.2","0.1.0-rc.3","0.1.0-rc.4","0.1.0-rc.5","0.2.0-rc.1","0.2.0-rc.2","0.3.0","0.3.1","0.3.3","0.3.4","0.3.5","0.4.0","0.4.1","0.4.2","0.4.3","0.4.4","0.4.5","0.5.0","0.5.1","0.5.2","0.6.0","0.6.1"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'bower'
npm ERR! notarget 
</code>

Seems to be some dependency Issue with npm related to it's version of bower.

**Comment by wwebfor** [comment]
You're right it's a dependency issue. Probably you just need to remove PhantomCSS, CasperJS, and PhantomJs from the file package.json.

If you don't want to remove dependencies by hand, you can just replace ``package.json`` with [this file][1].

[1]: https://github.com/Laverna/laverna/raw/master/package.json

**Comment by jcrben** [comment]
Seems to work if you just remove grunt-contrib-phantomcss.  Seems that project is currently abandoned.

`README` should be updated.
