### ISSUE TITLE
Blank white screen on iOS mobile after selecting "Start using now"

### ISSUE THREAD

**Issue by cblupodev** [Laverna/laverna#266]
Browser info [[aboutbrowser.com]](http://aboutbrowser.com/view/jdrLv)

---

![asdf](https://lh3.googleusercontent.com/wX5t4A0trlKUXu8b-joIoTlEJ6x2hO7IP7gjWGRe3Jiz=w542-h963-no)
![asdf](https://lh3.googleusercontent.com/n-TDxW9-hs4nC77apjuD_Fj7WqVE-duo_rR9pr6sypet=w542-h963-no)

**Comment by wwebfor** [comment]
I think it was related to all Webkit based browsers. Probably the issue was resolved. Can you confirm it?

**Comment by wwebfor** [comment]
Closing the issue. If the issue still persists, feel free to re-open it.
