### ISSUE TITLE
Spellchecker for the editor

### ISSUE THREAD

**Issue by vitr** [Laverna/laverna#268]
Spellchecker is available in the title but not in the editor, strange, even github has it

![image](https://cloud.githubusercontent.com/assets/2770290/9255576/a145f73e-422d-11e5-8d10-35860d4f4468.png)

**Comment by claell** [comment]
+1

**Comment by vitr** [comment]
correction, github has spelling for comments only, not for the file editor, so, perhaps, this is not an easy task((

**Comment by andtheWings** [comment]
+1

**Comment by yoachim** [comment]
+1
I can't spell for shit anymore.

**Comment by wwebfor** [comment]
The feature now works in dev branch.
