### ISSUE TITLE
Select notebook automatically

### ISSUE THREAD

**Issue by romu70** [Laverna/laverna#271]
Hi, here is an enhancement proposal.
Current use case:

Pre-requisite: select a notebook
1. Click on the new note button
-> The notebook for this new note is empty

Proposal: The notebook of the note is the notebook which was previously selected.

**Comment by Rantanen** [comment]
Bah. Github doesn't recognize "Implements" as one of auto-closing keywords.

@wwwredfish I believe this issue could be closed now, thanks to PR #289 being merged.

Or are you waiting for the changes to hit `master` before closing the issues?

**Comment by wwwredfish** [comment]
Ok. Thanks for your pull request and help.
