### ISSUE TITLE
Blocker: Loose data 

### ISSUE THREAD

**Issue by romu70** [Laverna/laverna#272]
Hi,
I've been using Laverna for some months now, and I'll probably quit because of recurrent data loose. My use case is pretty simple:

- Laverna is connected to my DropBox account
- I use it on 2 PCs
- I may not close my Firefox Laverna page when I put a PC in standby when leaving my job.

So when I come to work on the morning, I click on the Laverna refresh button, nothing happens and if I do some changes in a note and save it. All changes made on my other PC are gone.

Sorry, for this, but that's really a showstopper issue for me.

**Comment by wwebfor** [comment]
I see. We know that currently synchronization is broken in the app. We are working on solving that problem and it is our top priority right now. We are very sorry for your data loss.

**Comment by romu70** [comment]
Didn't know sync is broken. Fortunately is was not critical data. Great to read it's tracked. Thanks.

**Comment by romu70** [comment]
Great to see it works again, so I'm back to Laverna!! I think we can close this ticket. But if you want to keep it open, so be it.

**Comment by wwwredfish** [comment]
Are you using dev branch with remoteStorage or master branch with Dropbox?

**Comment by romu70** [comment]
Master branch with DropBox for the time being. Hope to be able to switch to RemoteStorage as soon as I can (need work on my Synology nas for that).

**Comment by wwwredfish** [comment]
It's strange, we haven't merged any new changes with master branch...

**Comment by romu70** [comment]
Yes, strange. The issue may have come a problem from one of my clients (2 PCs + 1 smartphone). I'll continue my testing to see how things are going.

**Comment by wwwredfish** [comment]
Thanks for your collaboration.

**Comment by romu70** [comment]
You're welcome. That's my small contribution, and my pleasure.

**Comment by claell** [comment]
Currently cloud sync with dropbox works for me as well on the normal Laverna website. So there might be only a few bugs and it is not completely broken, right?

**Comment by wwebfor** [comment]
I think it can be closed now. If anyone encounters problems, we can reopen it again.
