### ISSUE TITLE
A note is searchable, but does not appear in the main content frame

### ISSUE THREAD

**Issue by bkdonline** [Laverna/laverna#275]
I have a note, which has an entry in the notes section. When I click on the note in the left hand side menu, it does not open anything at all on right side, for this particular note.

I tried doing this in firefox, chrome, incongnito in both.

It will be good if I can recover this note, as it was a long piece, and a lot of information was inside it.

**Comment by wwebfor** [comment]
If I understood correctly, you can open other notes, right? In that case try to click on the note. That should change URL of the page to something like this ``https://laverna.cc/index.html#notes/p0/show/9281134b-520e-1ba6-0410-1da92993cdb2``.

After doing so, try to replace everything in the URL except for ID of the note. For instance, the previous URL should look like this ``https://laverna.cc/index.html#notes/edit/9281134b-520e-1ba6-0410-1da92993cdb2``. And open new URL in your browser. It should open edit page. If edit page isn't visible either, please open your browser console and try to find logs with error.

**Comment by bkdonline** [comment]
Upon loading the URL for the unloadable note, following is the output in
console.

GET
https://laverna.cc/index.html#/p/trainings/notes/p0/show/7e70b41d-d3b0-c74f-5b9e-62ca061f96fd
[HTTP/1.1 200 OK 0ms]
GET
https://laverna.cc/styles/90fa3c87.main.css [HTTP/1.1 200 OK 0ms]
GET
https://laverna.cc/scripts/vendor/1a5317ff.modernizr.js [HTTP/1.1 200 OK
0ms]
GET
https://laverna.cc/bower_components/requirejs/require.js [HTTP/1.1 200 OK
0ms]
Unknown pseudo-class or pseudo-element '-webkit-inner-spin-button'.
Ruleset ignored due to bad selector. 90fa3c87.main.css:9:1429
Unknown pseudo-class or pseudo-element '-webkit-search-cancel-button'.
Ruleset ignored due to bad selector. 90fa3c87.main.css:9:1663
Expected color but found 'auto'.  Expected color but found
'-webkit-focus-ring-color'.  Expected end of value but found
'-webkit-focus-ring-color'.  Error in parsing value for 'outline'.
Declaration dropped. 90fa3c87.main.css:9:3394
Expected end of value but found '\9 '.  Error in parsing value for
'margin-top'.  Declaration dropped. 90fa3c87.main.css:9:23359
Expected color but found 'auto'.  Expected color but found
'-webkit-focus-ring-color'.  Expected end of value but found
'-webkit-focus-ring-color'.  Error in parsing value for 'outline'.
Declaration dropped. 90fa3c87.main.css:9:23603
Unknown pseudo-class or pseudo-element '-ms-input-placeholder'.  Ruleset
ignored due to bad selector. 90fa3c87.main.css:9:24454
Unknown pseudo-class or pseudo-element '-webkit-input-placeholder'.
Ruleset ignored due to bad selector. 90fa3c87.main.css:9:24502
Unknown property 'user-select'.  Declaration dropped.
90fa3c87.main.css:9:29855
Expected color but found 'auto'.  Expected color but found
'-webkit-focus-ring-color'.  Expected end of value but found
'-webkit-focus-ring-color'.  Error in parsing value for 'outline'.
Declaration dropped. 90fa3c87.main.css:9:29940
Expected 'none', URL, or filter function but found 'alpha('.  Error in
parsing value for 'filter'.  Declaration dropped. 90fa3c87.main.css:9:30307
Expected 'none', URL, or filter function but found 'progid'.  Error in
parsing value for 'filter'.  Declaration dropped. 90fa3c87.main.css:9:38363
Error in parsing value for 'background-image'.  Declaration dropped.
90fa3c87.main.css:9:61366
Error in parsing value for 'background-image'.  Declaration dropped.
90fa3c87.main.css:9:61982
Error in parsing value for 'background-image'.  Declaration dropped.
90fa3c87.main.css:9:62427
Error in parsing value for 'background-image'.  Declaration dropped.
90fa3c87.main.css:9:62878
Error in parsing value for 'background-image'.  Declaration dropped.
90fa3c87.main.css:9:63327
Unknown property 'zoom'.  Declaration dropped. 90fa3c87.main.css:9:63713
Expected 'none', URL, or filter function but found 'alpha('.  Error in
parsing value for 'filter'.  Declaration dropped. 90fa3c87.main.css:9:67029
Expected 'none', URL, or filter function but found 'alpha('.  Error in
parsing value for 'filter'.  Declaration dropped. 90fa3c87.main.css:9:67138
Expected 'none', URL, or filter function but found 'alpha('.  Error in
parsing value for 'filter'.  Declaration dropped. 90fa3c87.main.css:9:68266
Expected 'none', URL, or filter function but found 'alpha('.  Error in
parsing value for 'filter'.  Declaration dropped. 90fa3c87.main.css:9:68320
Expected 'none', URL, or filter function but found 'alpha('.  Error in
parsing value for 'filter'.  Declaration dropped. 90fa3c87.main.css:9:69163
Expected 'none', URL, or filter function but found 'alpha('.  Error in
parsing value for 'filter'.  Declaration dropped. 90fa3c87.main.css:9:69210
Expected 'none', URL, or filter function but found 'alpha('.  Error in
parsing value for 'filter'.  Declaration dropped. 90fa3c87.main.css:9:73105
Error in parsing value for 'background-image'.  Declaration dropped.
90fa3c87.main.css:9:73244
Expected 'none', URL, or filter function but found 'progid'.  Error in
parsing value for 'filter'.  Declaration dropped. 90fa3c87.main.css:9:73455
Error in parsing value for 'background-image'.  Declaration dropped.
90fa3c87.main.css:9:73625
Expected 'none', URL, or filter function but found 'progid'.  Error in
parsing value for 'filter'.  Declaration dropped. 90fa3c87.main.css:9:73836
Expected 'none', URL, or filter function but found 'alpha('.  Error in
parsing value for 'filter'.  Declaration dropped. 90fa3c87.main.css:9:74055
Expected end of value but found '\9 '.  Error in parsing value for
'background-color'.  Declaration dropped. 90fa3c87.main.css:9:74996
Unknown pseudo-class or pseudo-element '-ms-input-placeholder'.  Ruleset
ignored due to bad selector. 90fa3c87.main.css:9:81670
Unknown pseudo-class or pseudo-element '-webkit-input-placeholder'.
Ruleset ignored due to bad selector. 90fa3c87.main.css:9:81735
Unknown property 'speak'.  Declaration dropped. 90fa3c87.main.css:9:93985
Unknown property 'speak'.  Declaration dropped. 90fa3c87.main.css:9:119476
Expected media feature name but found 'touch-enabled'. index.html:1:8
Expected media feature name but found '-webkit-touch-enabled'.
index.html:1:24
Expected media feature name but found '-o-touch-enabled'. index.html:1:69
Expected media feature name but found '-ms-touch-enabled'. index.html:1:88
Expected media feature name but found 'modernizr'. index.html:1:108
Unknown property '-moz-opacity'.  Declaration dropped. index.html
Error in parsing value for 'background-image'.  Declaration dropped.
index.html
Expected color but found 'left'.  Error in parsing value for
'background-image'.  Declaration dropped. index.html
Error in parsing value for 'background-image'.  Declaration dropped.
index.html
Error in parsing value for 'background-image'.  Declaration dropped.
index.html
Error in parsing value for 'background-image'.  Declaration dropped.
index.html
GET
https://laverna.cc/scripts/96b2d9d9.main.js [HTTP/1.1 200 OK 0ms]
GET
https://laverna.cc/styles/90fa3c87.main.css [HTTP/1.1 200 OK 0ms]
GET
https://laverna.cc/styles/90fa3c87.main.css [HTTP/1.1 200 OK 0ms]
GET
https://laverna.cc/styles/90fa3c87.main.css [HTTP/1.1 200 OK 0ms]
GET
https://laverna.cc/styles/90fa3c87.main.css [HTTP/1.1 200 OK 0ms]
GET
https://laverna.cc/styles/90fa3c87.main.css [HTTP/1.1 200 OK 0ms]
GET
https://laverna.cc/styles/90fa3c87.main.css [HTTP/1.1 200 OK 0ms]
GET
https://laverna.cc/styles/90fa3c87.main.css [HTTP/1.1 200 OK 0ms]
GET
https://laverna.cc/styles/90fa3c87.main.css [HTTP/1.1 200 OK 0ms]
GET
https://laverna.cc/styles/90fa3c87.main.css [HTTP/1.1 200 OK 0ms]
GET
https://laverna.cc/styles/90fa3c87.main.css [HTTP/1.1 200 OK 0ms]
GET
https://laverna.cc/styles/90fa3c87.main.css [HTTP/1.1 200 OK 0ms]
GET
https://laverna.cc/styles/90fa3c87.main.css [HTTP/1.1 200 OK 0ms]
GET
https://laverna.cc/styles/90fa3c87.main.css [HTTP/1.1 200 OK 0ms]
GET
https://laverna.cc/styles/90fa3c87.main.css [HTTP/1.1 200 OK 0ms]
GET
https://laverna.cc/styles/90fa3c87.main.css [HTTP/1.1 200 OK 0ms]
GET
https://laverna.cc/styles/90fa3c87.main.css [HTTP/1.1 200 OK 0ms]
GET
https://laverna.cc/styles/90fa3c87.main.css [HTTP/1.1 200 OK 0ms]
GET
https://laverna.cc/styles/90fa3c87.main.css [HTTP/1.1 200 OK 0ms]
GET
https://laverna.cc/styles/90fa3c87.main.css [HTTP/1.1 200 OK 0ms]
GET
https://laverna.cc/styles/90fa3c87.main.css [HTTP/1.1 200 OK 0ms]
GET
https://laverna.cc/styles/90fa3c87.main.css [HTTP/1.1 200 OK 0ms]
GET
https://laverna.cc/styles/90fa3c87.main.css [HTTP/1.1 200 OK 0ms]
GET
https://laverna.cc/bower_components/remotestorage.js/release/0.10.0-beta3/remotestorage-nocache.amd.js
[HTTP/1.1 200 OK 1086ms]
GET
https://laverna.cc/scripts/libs/dropbox.js [HTTP/1.1 200 OK 0ms]
GET
XHR
https://laverna.cc/locales/en-US/translation.json [HTTP/1.1 404 Not Found
296ms]
GET
XHR
https://laverna.cc/locales/en/translation.json [HTTP/1.1 200 OK 295ms]
GET
XHR
https://laverna.cc/locales/en-US/translation.json [HTTP/1.1 200 OK 0ms]
GET
https://laverna.cc/bower_components/MathJax/MathJax.js [HTTP/1.1 200 OK
583ms]
Keybindings has been reseted 96b2d9d9.main.js:28:9023
Keybindings has been restarted 96b2d9d9.main.js:28:9023
AppNote is started 96b2d9d9.main.js:28:9023
opening database trainings in version #6 96b2d9d9.main.js:9:4338
GET
https://laverna.cc/bower_components/MathJax/config/TeX-AMS-MML_HTMLorMML.js
[HTTP/1.1 200 OK 940ms]
execute : read on notebooks for undefined 96b2d9d9.main.js:9:4338
execute : read on notes for undefined 96b2d9d9.main.js:9:4338
execute : read on notes for 7e70b41d-d3b0-c74f-5b9e-62ca061f96fd
96b2d9d9.main.js:9:4338
TypeError: b is null 96b2d9d9.main.js:13:18931
execute : read on notebooks for undefined 96b2d9d9.main.js:9:4338
execute : read on notes for undefined 96b2d9d9.main.js:9:4338
execute : read on removed for undefined 96b2d9d9.main.js:9:4338
GET
XHR
https://api19.dropbox.com/1/metadata/auto/trainings/notes [HTTP/1.1 200 OK
1003ms]
Unknown property '-moz-border-radius'.  Declaration dropped. index.html:1:92
Unknown property '-moz-box-shadow'.  Declaration dropped. index.html:1:215
Unknown property '-moz-border-radius'.  Declaration dropped.
index.html:1:476
Unknown property '-moz-box-shadow'.  Declaration dropped. index.html:1:605
Expected 'none', URL, or filter function but found 'progid'.  Error in
parsing value for 'filter'.  Declaration dropped. index.html:1:680
Unknown property '-moz-border-radius'.  Declaration dropped.
index.html:2:428
Unknown property '-moz-box-shadow'.  Declaration dropped. index.html:2:555
Expected 'none', URL, or filter function but found 'progid'.  Error in
parsing value for 'filter'.  Declaration dropped. index.html:2:630
Unknown property '-moz-box-shadow'.  Declaration dropped. index.html:1:467
Expected 'none', URL, or filter function but found 'progid'.  Error in
parsing value for 'filter'.  Declaration dropped. index.html:1:540
Expected 'none', URL, or filter function but found 'alpha('.  Error in
parsing value for 'filter'.  Declaration dropped. index.html:2:202
Expected 'none', URL, or filter function but found 'alpha('.  Error in
parsing value for 'filter'.  Declaration dropped. index.html:4:177
GET
https://laverna.cc/bower_components/MathJax/images/MenuArrow-15.png
[HTTP/1.1 200 OK 319ms]
GET
XHR
https://api-content.dropbox.com/1/files/auto/trainings/notes/2cafe2f6-73b8-4550-a7e8-5c1f8aa7a743.json
[HTTP/1.1 200 OK 1371ms]
GET
XHR
https://api-content.dropbox.com/1/files/auto/trainings/notes/7e70b41d-d3b0-c74f-5b9e-62ca061f96fd.json
[HTTP/1.1 200 OK 1047ms]
GET
XHR
https://api-content.dropbox.com/1/files/auto/trainings/notes/90eef249-0698-b64a-bad9-057b4f42dc09.json
[HTTP/1.1 200 OK 1015ms]
Sync done: notes 96b2d9d9.main.js:28:9023
execute : read on notebooks for undefined 96b2d9d9.main.js:9:4338
execute : read on removed for undefined 96b2d9d9.main.js:9:4338
GET
XHR
https://api30.dropbox.com/1/metadata/auto/trainings/notebooks [HTTP/1.1 200
OK 1254ms]
GET
XHR
https://api-content.dropbox.com/1/files/auto/trainings/notebooks/a218a024-4ee0-67a9-93dd-16e695450f35.json
[HTTP/1.1 200 OK 457ms]
Sync done: notebooks 96b2d9d9.main.js:28:9023
execute : read on tags for undefined 96b2d9d9.main.js:9:4338
execute : read on removed for undefined 96b2d9d9.main.js:9:4338
GET
XHR
https://api30.dropbox.com/1/metadata/auto/trainings/tags [HTTP/1.1 404 Not
Found 402ms]
Sync done: tags 96b2d9d9.main.js:28:9023
execute : read on files for undefined 96b2d9d9.main.js:9:4338
execute : read on removed for undefined 96b2d9d9.main.js:9:4338
GET
XHR
https://api10.dropbox.com/1/metadata/auto/trainings/files [HTTP/1.1 404 Not
Found 856ms]
Sync done: files 96b2d9d9.main.js:28:9023
SYNC DONE 96b2d9d9.main.js:28:9023
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.

**Comment by bkdonline** [comment]
editing the URL to notes/edit/... works. I can see the full content of my note. How to view the note too in preview mode?

**Comment by bkdonline** [comment]
Okay - this is the issue. My note had `<pre><!DOCTYPE html></pre>` as its content. Removing this is rendering the note properly.

Surprisingly, just removing `<!DOCTYPE html>` does not help.

May be this can be marked as a bug.

**Comment by wwebfor** [comment]
I believe we fixed it. If it isn't the case,we can reopen it again.
