### ISSUE TITLE
Can't decrypt notes

### ISSUE THREAD

**Issue by TheBlueGhost** [Laverna/laverna#276]
I took some notes on one machine, encrypted them, and backed them up to Dropbox. I synchronised them to a different machine and now I don't know how to decrypt them. Is this a bug or have I missed a step which is necessary to get decryption to work?

Can files even be decrypted on another computer through Laverna?

**Comment by Poorchop** [comment]
Once you set up encryption, you have to export your settings. You can find this option in the "Other" tab. If you try to access your Laverna notes via another computer, you have to import the aforementioned settings file, and then you will be able to enter your password to decrypt your notes.

**Comment by TheBlueGhost** [comment]
Ah, that explains that. I've stupidly lost a few notes but I'll keep this in mind for the future. Thank you for such a quick response too, by the way.

**Comment by dhimmel** [comment]
> Once you set up encryption, you have to export your settings. You can find this option in the "Other" tab. If you try to access your Laverna notes via another computer, you have to import the aforementioned settings file, and then you will be able to enter your password to decrypt your notes.

This is really counterintuitive. From a usability perspective, you should be able to connected to encrypted notes with a dropbox authorization and encryption password.

**Comment by Poorchop** [comment]
You would rather passwords be stored in plaintext then? Take a minute to read about [password hashing](https://en.wikipedia.org/wiki/Salt_(cryptography)). If it's a nightmare to copy and paste a settings file onto another computer, then you might be doing some incorrectly.

**Comment by dhimmel** [comment]
> You would rather passwords be stored in plaintext then?

I don't follow. The settings (including the salt) could be stored with the encrypted payload in Dropbox. No password is being stored. Right now it's confusing to have a "settings" file, which acts like a partial "key". It's easy for users to overlook the need to backup their settings.

I certainly may be configuring Laverna wrong -- the UI doesn't make it clear how to connect from an existing Dropbox store. Right now, I'm experiencing an issue where two computers share some notes, but have begun writing new encrypted files that the other cannot decrypt. It's a mess. Services such as [airBitz](https://airbitz.co/) have done a good job making client-side decryption painless. I'm just suggesting that somethings a little off in the Laverna cloud-storage-with-encryption workflow. It's hard to nail down exactly what isn't working, just that I've struggled.

**Comment by wwebfor** [comment]
I see your point @dhimmel. You are working on improving this issue.
