### ISSUE TITLE
Update/fix remoteStorage support

### ISSUE THREAD

**Issue by skddc** [Laverna/laverna#279]
There are several issues, which have been open for quite a long time. Some of them will be solved by just upgrading the remoteStorage.js library and Laverna's module for it. Here's a short list of issues with open ends:

* https://github.com/Laverna/laverna/issues/76
* https://github.com/Laverna/laverna/issues/31
* https://github.com/Laverna/laverna/issues/246
* https://github.com/Laverna/laverna/issues/255

The last one is actually about updating RS support and the module, and it sounds like it was almost finished, but then abandoned.

I'm opening this issue so we can track the state of these somehow and more importantly the overall upgrade/support status.

There are many people who want to use Laverna with remoteStorage, myself included, and it seems like there's not much missing for that. So I'm also posting a bounty for working remoteStorage support (tested with sync across browsers/devices) on Bountysource. Thank you, Laverna devs, for making this great app! Would be fantastic if we can get RS sorted out as well, so more people can get on board.

Edit: 2 BTC (~$485) bounty posted at https://www.bountysource.com/issues/27002492-update-fix-remotestorage-support

**Comment by skddc** [comment]
FYI, we just released remoteStorage.js 0.12.0: https://community.remotestorage.io/t/remotestorage-js-0-12-0-released/

**Comment by wwwredfish** [comment]
We rewrote RemoteStorage module and we will soon release a new version of the app. We will try to ask if those issues are solved then. We have been testing it ourselves for a week or so, and it seems like it works. We also wrote some Nightwatch tests for it.

**Comment by skddc** [comment]
![thumbs-up-daft-punk](https://cloud.githubusercontent.com/assets/842/11558946/685e40d4-99ad-11e5-8f37-0108bb91e084.gif)

**Comment by skddc** [comment]
It mostly works for me, but sometimes FF doesn't update notes when they have changed. Oftentimes it does, though, and I still haven't found out when or why it failed.

**Comment by skddc** [comment]
Just a reminder that there's still [a bounty to collect](https://www.bountysource.com/issues/27002492-update-fix-remotestorage-support) for this issue. The issues I linked initially have all been closed and it looks to me like everything's done so far.

**Comment by wwebfor** [comment]
OK. I guess we can close this issue ;).

**Comment by wwebfor** [comment]
Thank you very much @skddc for your support :)

**Comment by skddc** [comment]
Thanks for supporting open protocols! :)
