### ISSUE TITLE
You can export Evernote? 

### ISSUE THREAD

**Issue by tanrax** [Laverna/laverna#282]
I mention this because if you were that button would be great!

**Comment by jcrben** [comment]
Not sure I understand this issue, but it seems like a duplicate of https://github.com/Laverna/laverna/issues/45 and could probably be closed.

**Comment by claell** [comment]
Maybe he wants an option to export the notes from Laverna to Evernote?

**Comment by tanrax** [comment]
No, I want the opposite

**Comment by claell** [comment]
Then it is a duplicate of #45 right?

**Comment by wwebfor** [comment]
Close the issue since it is a duplicate.
