### ISSUE TITLE
Icon missing on homepage

### ISSUE THREAD

**Issue by gunar** [Laverna/laverna#283]
Sorry, don't know where else to post this. On [laverna.cc](http://laverna.cc) the MarkDown icon is missing.

![laverna](https://cloud.githubusercontent.com/assets/7684574/10339141/3e336a72-6ce0-11e5-8255-e9a06a936b40.png)

This

    <li><i class="icon-star"></i> Markdown</li>

show become

    <li><i class="icon-star-empty"></i> Markdown</li>

.

**Comment by wwebfor** [comment]
I believe the issue can be closed since the home page was redesigned.
