### ISSUE TITLE
backbone-indexeddb connection error

### ISSUE THREAD

**Issue by jcrben** [Laverna/laverna#288]
I got the following message from backbone-indexeddb sometimes: `Couldn't not connect to the database` (seems like that library needs to fix its double negative). Digging in a bit more, `e.srcElement.error.message` has this: `The requested version (6) is less than the existing version (7).` It's a `VersionError` (seems to be an official IndexedDB thing).

This might be a niche development problem. It came as I was doing some `git reset --hard` to `git bisect` a problem with tags. It seems that the schema in `app/scripts/migrations/note.js` goes up to version 6 in the current version but I must have grabbed a higher version later.

I was able to get it working again (I think) by manually deleting the database: first listed dbs [per this](http://stackoverflow.com/questions/15234363/indexeddb-view-all-databases-and-object-stores) and then ran `indexedDB.deleteDatabase('notes-db');` from the console. But maybe the application could fixed to recover from these types of errors on its own.

**Comment by wwebfor** [comment]
You're right. We solved this by switching to localForage. It doesn't depend on database versions.
