### ISSUE TITLE
Enhancement: Editing on a smartphone is not good enough

### ISSUE THREAD

**Issue by romu70** [Laverna/laverna#293]
Hi, it's logical to split the screen vertically on a desktop, because the screen has an horizontal orientation. On a smartphone, it's just the opposite. I guess a tabbed interface (one tab for editing, one tab for preview), would be better. Or any other satisfying solution, of course.

**Comment by wwebfor** [comment]
In the next version the app will have a tabbed view on smartphones.
It will look something like that:

![smartphone](https://cloud.githubusercontent.com/assets/2404615/10939021/c1f08c88-8328-11e5-8672-9e628203a36b.png)

What is your opinion? Is it good enough?

**Comment by romu70** [comment]
I wouldn't have dreamt of a better thing, looks really great. Obviously some huge changes are coming, is there any ETA?

**Comment by wwebfor** [comment]
Hopefully by the end of this month we will release a new version.

**Comment by romu70** [comment]
Great, can't wait !!

**Comment by gaartsen** [comment]
Great news indeed
