### ISSUE TITLE
Infinite loading icon when there are no notes

### ISSUE THREAD

**Issue by claell** [Laverna/laverna#301]
![bildschirmfoto vom 2015-12-04 22-53-47](https://cloud.githubusercontent.com/assets/6171135/11602356/ef2e7ba6-9ad9-11e5-9de3-c8b94372a668.png)
I do not have any notes, but there is an infinite loading icon.

**Comment by wwebfor** [comment]
I believe the issue was resolved.

**Comment by claell** [comment]
Yes, thanks for fixing.
