### ISSUE TITLE
Sorting by name does not seem to work.

### ISSUE THREAD

**Issue by claell** [Laverna/laverna#303]
Title says it all. It appears that there are always the newest created notes on top.

**Comment by brpaz** [comment]
Yes. same issue. I would like to have my notes sorted by name, not only notebooks.

**Comment by talklittle** [comment]
It appears that the notebooks are being sorted by ID, which is randomly generated, rather than display name. Check this by hovering over the notebook links with your mouse cursor, and see that the URLs are sorted in order.

**Comment by claell** [comment]
Yes, I was talking about Notes. Did not read the setting carefully enough.
