### ISSUE TITLE
Category headline is not complete for me

### ISSUE THREAD

**Issue by claell** [Laverna/laverna#305]
![bildschirmfoto vom 2015-12-06 15-40-37](https://cloud.githubusercontent.com/assets/6171135/11613842/fd20a340-9c2f-11e5-84f7-d4fa06923652.png)

Example with favorites category.

**Comment by claell** [comment]
Thanks for fixing. Will close after I can successfully test it. Currently it does not seem to be already on laverna.cc/nightly

**Comment by claell** [comment]
@wwebfor am I to fast? Does not seem fixed on https://laverna.cc/nightly/ right now.

**Comment by claell** [comment]
Is fixed in the current nightly. Looks not very pretty, when hovering over it, though: 
![bildschirmfoto vom 2015-12-19 10-53-14](https://cloud.githubusercontent.com/assets/6171135/11912486/c50f6cf2-a63e-11e5-8d6c-6a38576f7756.png)

**Comment by claell** [comment]
Great, thanks for implementing this as well @ncpierson.

**Comment by wwebfor** [comment]
Can the issue be closed?

**Comment by claell** [comment]
Fixed in nightly, so yes, can be closed.
