### ISSUE TITLE
Add mention of desktop Electron app to site

### ISSUE THREAD

**Issue by bnvk** [Laverna/laverna#311]
Adding the Electron app is a pretty huge thing, IMHO, so I propose adding it to the laverna.cc website. You may already be doing this. I would have sent a pull-req myself, but don't see where the repo / code is.

But I did just send a [pull request](https://github.com/atom/electron.atom.io/pull/123) for the official Electron site, so it would be nice to have it on the site as well!

**Comment by wwebfor** [comment]
Thanks for that. We want to add the link after we redesign the website. (It was pointed out that it looks a little ugly :) )

**Comment by wwebfor** [comment]
It's done.
