### ISSUE TITLE
BUG: Can't edit on smartphone

### ISSUE THREAD

**Issue by romu70** [Laverna/laverna#312]
Hi,
I run Sailfish OS on my Nexus which uses a Gecko based browser. With the new Laverna, I can't edit a note. I can open the note, switch to edit mode, make some changes, but when I tap on the "save" button, nothing happens.

**Comment by romu70** [comment]
Another issue: when in edition mode, I can't scroll the markdown area.

**Comment by romu70** [comment]
More on this issue:
Create, edit, sync, delete, etc notes work on both smartphone and PCs.

The problem is with the notes created with the previous version of Laverna which can not be edited on both smartphone and PCs.

WORKAROUND: copy/paste old notes to new ones works.

**Comment by wwebfor** [comment]
Do you have notebooks or tags attached to those old notes?

**Comment by romu70** [comment]
Yes, it's related to #322, I just forgot to update this one. It can be closed.
