### ISSUE TITLE
Images no longer parsed properly

### ISSUE THREAD

**Issue by dmikalova** [Laverna/laverna#316]
The new markdown parser seems to trip up on images using `![]($url)` syntax and instead of displaying an image in place it reads it as ! then checkbox then ($url).

**Comment by wwebfor** [comment]
Yeah, it is a bug. We forgot to check it. Thanks for taking your time and reporting it.

**Comment by dmikalova** [comment]
Thanks, I love the product so far.

**Comment by wwebfor** [comment]
It was fixed in 0.7.2-RC.
