### ISSUE TITLE
Pasting broken

### ISSUE THREAD

**Issue by jdfm** [Laverna/laverna#317]
I am unable to paste text into Laverna.

I've tried copying from Chrome and TextEdit, it just doesn't work.

OSX El Capitan 10.11.2
Laverna 0.7.0

**Comment by wwebfor** [comment]
Thanks for reporting the bug. We will try to fix it.

**Comment by athiele** [comment]
Also not working with the Desktop app in Yosemite

**Comment by athiele** [comment]
Pull request pending, see #326
