### ISSUE TITLE
Note unreadable from one device to another

### ISSUE THREAD

**Issue by alexsourcerer** [Laverna/laverna#318]
I created a note with Firefox with some formatting.
I saved my note. I opened laverna with my ubuntu touch device, the note was here but not readable.
It was just an amount of letters, signs, and numbers.
![screenshot20151210_112638761](https://cloud.githubusercontent.com/assets/11145952/11713090/7309f544-9f31-11e5-82cf-6959d79f2962.png)
![screenshot20151210_112645385](https://cloud.githubusercontent.com/assets/11145952/11713091/730b48a4-9f31-11e5-8c00-e51a58ead8fb.png)

**Comment by claell** [comment]
Did you activate encryption?

**Comment by wwwredfish** [comment]
You need to import settings from your Firefox.

**Comment by alexsourcerer** [comment]
You are right, I made that mistake of not importing settings.
On Ubuntu touch, though, taping on "déverrouiller" ("unlock", in english?) is not working, I need to press the "enter" key of the virtual keyboard.

**Comment by wwwredfish** [comment]
I see. We will look into it. Thanks for your contribution.
