### ISSUE TITLE
BUG: Can't scroll the markdown area

### ISSUE THREAD

**Issue by romu70** [Laverna/laverna#320]
My Nexus 5 runs Sailfish OS which runs a Gecko based browser. In edit mode, scrolling the markdown area is not possible.

**Comment by wwebfor** [comment]
Thanks for reporting the bug. We will try to fix it ASAP.

**Comment by romu70** [comment]
Thanks. Reporting bug is my way to help as much as possible. Thanks a lot for this amazing app.

**Comment by claell** [comment]
Same here with Firefox on Android.

**Comment by claell** [comment]
Works now with the nightly version.
