### ISSUE TITLE
Question or BUG?: How to set a notebook

### ISSUE THREAD

**Issue by romu70** [Laverna/laverna#322]
Tested on both smartphone and PC with Firefox, I didn't find any way to choose the notebook for a given note.

The "Add a notebook" action works as expected, but not the "select" one.

**Comment by romu70** [comment]
The problem seems to come the notebooks created with the old Laverna are not seen by this new version.

Create new notebooks, and affect to notes, works as expected. But the old notebooks can't be selected and are not listed in the notebooks list.

**Comment by wwebfor** [comment]
@romu70 because notebooks used to be a little different in previous versions, you need to migrate them. To do so, open https://laverna.cc/nightly/migrate.html

**Comment by wwebfor** [comment]
I hope it worked :)

**Comment by romu70** [comment]
Yes of course. It was also related to #321. I moved my around 60 notes manually to the new notebook management and it works as expected. Thanks.
