### ISSUE TITLE
"[]" causes the displayed version to insert html code for a checkbox

### ISSUE THREAD

**Issue by can-z** [Laverna/laverna#324]
# Steps to reproduce:
* Type "[]" (no quotes) inside a \`\` (code snippet) block.
* Observe that the displayed version has `<label class="task checkbox"><input data-task="1" type="checkbox" class="checkbox--input" /><svg class="checkbox--svg" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><path class="checkbox--path" d="M16.667,62.167c3.109,5.55,7.217,10.591,10.926,15.75 c2.614,3.636,5.149,7.519,8.161,10.853c-0.046-0.051,1.959,2.414,2.692,2.343c0.895-0.088,6.958-8.511,6.014-7.3 c5.997-7.695,11.68-15.463,16.931-23.696c6.393-10.025,12.235-20.373,18.104-30.707C82.004,24.988,84.802,20.601,87,16"></path></svg><span class="checkbox--text">` in place of the "[]".

**Comment by wwebfor** [comment]
It was fixed in 0.7.2-RC
