### ISSUE TITLE
unable to launch desktop after update to rc2

### ISSUE THREAD

**Issue by eMerzh** [Laverna/laverna#336]
i had the rc installed,
the i've downloaded the new rc2 to fix the copy past thing ...
and now i can't start the app .... white screen ... nothing more
 0.7.1-RC2 

osx 10.11.1 x64

**Comment by wwwredfish** [comment]
Got it. Will fix it ASAP. Can you for now use RC1/7.0.0?

**Comment by eMerzh** [comment]
Of course ;)
Keep up the good work ! But don't wait tooooo much to release the new version ;)

**Comment by wwebfor** [comment]
@eMerzh we released a new version. Hopefully this bug isn't present there.

**Comment by eMerzh** [comment]
yes, perfect ;-)

thanks
