### ISSUE TITLE
Note is still displayed after permanently deleting it

### ISSUE THREAD

**Issue by claell** [Laverna/laverna#337]
I experienced that a note is still displayed after deleting it permanently:
![bildschirmfoto vom 2015-12-19 11-15-04](https://cloud.githubusercontent.com/assets/6171135/11912557/ce877092-a641-11e5-936b-d75e8c776863.png)

**Comment by claell** [comment]
Fixed in Beta v0.7.2-RC3, thank you!

**Comment by wwebfor** [comment]
You are welcome :)
