### ISSUE TITLE
List rendering issues

### ISSUE THREAD

**Issue by claell** [Laverna/laverna#338]
When creating a list and hitting enter, the next list symbol is created automatically. However, if one does not type any text behind it, the rendering is a bit unexpected:

![bildschirmfoto vom 2015-12-19 11-08-29](https://cloud.githubusercontent.com/assets/6171135/11912568/4d2c857c-a642-11e5-949e-71441a5bc7e2.png)
![bildschirmfoto vom 2015-12-19 11-08-52](https://cloud.githubusercontent.com/assets/6171135/11912569/4d2f9866-a642-11e5-9d54-758d5b938836.png)

**Comment by wwebfor** [comment]
I think it was already fixed by switching to Markdown-it. Can you confirm it?

**Comment by claell** [comment]
Yes, this is fixed in nightly version.
