### ISSUE TITLE
Inline Math Support

### ISSUE THREAD

**Issue by siqil** [Laverna/laverna#339]
I noticed Laverna uses MathJax, and display style equations in `$$ ... $$` are rendered correctly, but does it support inline math, like `$a$`, or `$E = m c ^ 2$`? I tried (on both Firefox and Chrome), but they are not rendered as math.

**Comment by dpvc** [comment]
Did you try `\(...\)` rather than `$...$`.  MathJax's default configuration doesn't enable dollar-sign delimiters, since these are commonly used in other ways.  They can be enabled, however, so perhaps there is a way to do that through Laverna (I don't know the product).

**Comment by siqil** [comment]
Yes, I tried. Not working either.

**Comment by F-A** [comment]
I have the same problem on my machine. The inline $a$ does not work if inserted inside a senstence. However, it work if the equation is on a single line.
From Firefox debugger, it seems that Mathjax is not called for the math formula inserted in a sentence, only for formula on a separate line.

**Comment by wwebfor** [comment]
Can you check if it works in the pre-release version? (laverna.cc/nightly)

**Comment by siqil** [comment]
Yes, it works (on Firefox). Thanks.

**Comment by roiholtzman** [comment]
Should math symbols work in the online version? I'm running on Safari, and it doesn't work for me.

**Comment by iwasingh** [comment]
Not working on Debian 9 `laverna-0.7.1-linux-x64`
```Let A with $x$```
is rendered as
```Let A with $x$```

**Comment by funilrys** [comment]
Hi @iwasingh @siqil @F-A @dpvc,

Unfortunately, this issue will never be fixed here.

Please report to https://github.com/Laverna/laverna/issues/971#issuecomment-411423965 for the current state of this project and https://github.com/encryptic-team/encryptic for the future of this project.

Have a nice day/night.

Cheers,
Nissar
