### ISSUE TITLE
Is it possible encryption doesn't work on iOS browsers?

### ISSUE THREAD

**Issue by ryanl888** [Laverna/laverna#340]
Hello,
I tried using laverna with firefox and chrome browsers on iOS.  Originally, it worked very well.  However, I was interested in trying the encryption, and activated it on my account on my mac.  However, when I go to use laverna again on my iOS device - I get a loading page - and nothing. I have connected remote storage if this is relevant.

**Comment by wwebfor** [comment]
Hello,

Have you imported your settings to the other device?

**Comment by ryanl888** [comment]
@wwebfor,
No, I did not.  I found that if I go to https://laverna.cc/dist as mentioned here: [https://github.com/Laverna/laverna/issues/300] then it would work on my iPhone and (after about 24 hrs) sync to remote storage (although this seems buggy so I reverted to dropbox for now).  I am still unwilling to use encryption though - as I believe that is the cause of the problem on my iPhone.  FYI, https://laverna.cc/apps is still displaying the loading... error on it.

**Comment by wwebfor** [comment]
@ryanl888,
Thanks for the clarification. We'll look closer to this bug. FYI, the version on laverna.cc/dist is old. That's why RemoteStorage doesn't work there.

One more question. Did you start experiencing it after you enabled encryption on your iOS device? Was it working before you did that?

**Comment by wwebfor** [comment]
@ryanl888 can you describe what is says in the developer console when you open https://laverna.cc/app?

**Comment by ryanl888** [comment]
@wwebfor
1. AFAIK it was working well on my iPhone until I enabled encryption.
2. Unclear - do you want me to open this in a browser on my phone? Can I do that?  Or do you mean on desktop (where it is still working)?

**Comment by wwebfor** [comment]
2. I thought it wasn't working on your desktop. Sorry, I misunderstood.
