### ISSUE TITLE
Import data does not work

### ISSUE THREAD

**Issue by ryanmcnz** [Laverna/laverna#343]
The "Import data" feature for loading notes from a zip file does not currently work when using Laverna in either the browser or desktop app.

I ran into this issue while using the latest Chrome under Windows 7. The issue was also present in both the 32bit and 64bit desktop client for Windows, version 0.7.1.

Steps to reproduce:
- Run the latest version of Laverna via either downloading the desktop app or by accessing it at https://laverna.cc/app/.
- Create a test note. Give it a title and some content. Save the note.
- Click "Export data" in the Settings screen. This will successfully save the notes database to a zip file.
- Delete the test note in Laverna, ensuring it is also removed from the trash.
- Attempt to re-import the notes database by clicking "Import data" on the Settings screen and selecting the previously saved zip file.
- Navigate back to the list of notes. The previously saved test note will not be listed anywhere.

Expected outcome:
- The data should import successfully from the zip file.
- There should be one test note shown in the notes list.

Actual outcome:
- Nothing seems to happen. No notes are imported.

Additional details:

The export feature seems to work fine in both the browser and desktop app.
To double check that the exported data was correct, I looked into the exported notes database in the zip file:
- The default database name of "notes-db" is present.
- The test note is present inside the "notes" folder, as both a markdown and json file. The contents of these files also seem correct.

**Comment by wwwredfish** [comment]
Thank you for reporting this bug. We will start working on it.

**Comment by wwebfor** [comment]
I tried to reproduce what you've describe in this issue but everything works fine. Maybe it happens only on Windows?

**Comment by ryanmcnz** [comment]
I can confirm that it only appears to be happening on Windows.
The import is working successfully for me when I try it under Chrome via an Ubuntu Linux virtual machine (latest version of Chrome, and Ubuntu 15.10).

I wonder why it would have this problem under only Windows, and on both the browser and desktop versions of the app?

**Comment by wwebfor** [comment]
I don't know. We'll have to test it later :)

**Comment by claell** [comment]
File path issue?

**Comment by wwebfor** [comment]
Probably.

**Comment by GuyFromMars** [comment]
Same here. My Laverna cannot import data (the data was exported by a Ubuntu Laverna).

**Comment by GuyFromMars** [comment]
I tried to use the [web app](https://laverna.cc/) to import the data. I found that all the code blocks are changed to `&#x60;&#x60;&#x60`, thus they cannnot be rendered correctly.

**Comment by mobularays** [comment]
I am on using Desktop version of Laverna on Ubuntu 14.04.1 LTS and import data is not working in `laverna-0.7.3-linux-x64`. 
Previous version is: `laverna-0.7.1-linux-x64`

**Comment by maciakt** [comment]
This is still an issue for the windows 7, laverna 0.7.1.  It exports correctly (as I was able to import notes from this version onto a laverna for win10) but it will not import.  Just a blank screen.  I find it odd that it says this was fixed on Jun 15.  Maybe it is in the "latest" version not yet released but not in 0.7.1?

**Comment by tbaumann** [comment]
It's 2023 and it's still broken :/
