### ISSUE TITLE
HTML tags are taken out of notes

### ISSUE THREAD

**Issue by tucker-m** [Laverna/laverna#345]
Any HTML tags inside of a note get removed. For example, if you write this:

This is a note about the `<body>` tag.

It only saves "This is a node about the '' tag." 

If you try to write a `<script>` tag, it will delete all text after the tag. I'm guessing that this is to avoid scripts from being put on the page, but someone could've legitimately meant to write that (for example, if they're writing about an HTML application they're working on).

Could HTML tags be allowed in notes? Possibly escaped?

**Comment by wwebfor** [comment]
You're right we do it to avoid XSS. We use Dompurify to do that. The issue can be solved by configuring Dompurify.

**Comment by tucker-m** [comment]
I just had a look at DOMPurify and I couldn't find a way of making it do that. It has options for allowing certain tags, but not doing escape characters. I think what we really want to do is replace the `<` and `>` characters with `&lt;` and `&gt;`.

**Comment by jashgala** [comment]
How about using this simple technique? https://jsfiddle.net/e8hpnha6/

**Comment by wwebfor** [comment]
Starting from 0.7.3-RC3 we use Underscore's `unescape`. Can you check if the issue was fixed?

**Comment by wwebfor** [comment]
I think it was fixed.
