### ISSUE TITLE
Notebook selection widget looks horrible

### ISSUE THREAD

**Issue by romu70** [Laverna/laverna#346]
Hi,
Minor bug of course. I really like the smooth and simple look of Laverna, but guys, your notebook selection widget just looks horrible compared Laverna as a whole.

**Comment by wwebfor** [comment]
:)
If you mean native selectors (``<select>``), then we used them for simplicity. For instance, on mobile devices native selectors work beautifully. We don't have to handle responsiveness (it shows a popup window) and other mobile specific behaviours. Custom select menus typically don't have features like that.

Of course, if you have a suggestion how to improve it, we'll gladly hear it ;-)

**Comment by tucker-m** [comment]
Making select boxes look nice has always been such a pain. I'm in favor of using the native ones for the same reason wwebfor said.

You can style them a little, as shown here: http://bavotasan.com/2011/style-select-box-using-only-css/. However, that replaces the drop-down arrow with an image, and their widths have to be fixed. Unfortunately, I don't think there's any good way of mimicking the Edit/Remove drop-down button that's used on the list of notebooks.

**Comment by romu70** [comment]
Fair enough. I'm far from being a front end expert, so I don't have any suggestion to improve this. Thanks for the discussion, I close this.
