### ISSUE TITLE
Demo not working on "laverna.cc" website

### ISSUE THREAD

**Issue by jashgala** [Laverna/laverna#348]
Website in question: https://laverna.cc/index.html 

On the website when I click the start using now button, it does not open the editor. Instead it reloops back to the index.html page. I would suggest that it would be better to make it point to http://laverna.github.io/static-laverna/ or to show a message saying it is still under development (if it is the expected behavior at the current stage). The reason I suggest this is because I think it may cause confusion to newcomers to the site.

**Comment by wwwredfish** [comment]
We will fix it ASAP. Thanks for reporting it.

**Comment by wwebfor** [comment]
It was fixed. We just switched to another server and forgot to fix that link.

**Comment by wwebfor** [comment]
It was fixed. We just switched to another server and forgot to fix that link.
