### ISSUE TITLE
Logo for Laverna

### ISSUE THREAD

**Issue by wwwredfish** [Laverna/laverna#350]
Every serious project should have a decent logo. Unfortunately our current logo isn't great. That's why we started a design contest on DesignHill 10 days ago. We got some good logo designs, but now we are having problems with choosing.

If you would like to participate in choosing the logo, you can find the poll here:
http://laverna.displayer.io/00f11ff2

Edit: Additional designs http://laverna.displayer.io/64d170a3

**Comment by claell** [comment]
I just voted. I think that most logos are not really fitting the current style, though. Also none of has elements related with note taking unfortunately.

**Comment by wwwredfish** [comment]
@claell Thanks for voting!

**Comment by ryanmcnz** [comment]
I voted. The results were exactly what I expected too haha.
Also I second what @claell said, it seems as though most of these were not created to match the actual theme of the application.
Did the creators of these logos actually know it was a note-taking application?

**Comment by wwebfor** [comment]
@ryanmcnz I think they knew. At least we told them in the design contest it's a note taking app. And plus maybe we aren't good at choosing a logo :(.

**Comment by wwebfor** [comment]
We created a new poll with another batch of logos http://laverna.displayer.io/64d170a3. Maybe there are some concepts which fit the app.

**Comment by claell** [comment]
Just rated. I liked the font of the logo on the cardboard. Maybe one can create a corresponding icon fitting a bit better to it.

**Comment by ryanmcnz** [comment]
Voted again. There's two really good ones on that second batch. I'd like to see a non-printed version of the one that looks like its on paper, as that really wasn't helpful when judging the logo.

**Comment by wwebfor** [comment]
This is the last batch http://laverna.displayer.io/595e06d7. Others look even more horrendous :(

**Comment by claell** [comment]
Voted again. On the website of DesignHill they say that one can "Give Feedback & Get Unlimited Revisions". I would use this option (if it is free) and hopefully there are improved proposals which maybe combine some good aspects of the current proposals.

**Comment by ryanmcnz** [comment]
Vote on the last batch. Overall I think there's some nice ones to choose from, and a few definite choices that with a bit of iteration could be spot on.
This last batch seems to have much better color selections!

**Comment by wwebfor** [comment]
Thank you guys for your participation.
