### ISSUE TITLE
Feature: inline preformatted/code blocks

### ISSUE THREAD

**Issue by trestletech** [Laverna/laverna#362]
I'm finding that the markdown:
```
Do we want to move tracking to `jobs`?
```

Gets rendered as:
![screen shot 2016-01-19 at 11 35 51 am](https://cloud.githubusercontent.com/assets/1593639/12426745/e7a971ac-bea0-11e5-93d3-a2b4d197edd8.png)

I would expect/prefer that it get rendered inline as it does in e.g. GitHub:

Do we want to move tracking to `jobs`?

**Comment by wwebfor** [comment]
It is a bug in CSS and it is pretty easy to fix. We'll fix it later.

**Comment by ncpierson** [comment]
I noticed this, too! I would really love if this were fixed. I'm on it.

**Comment by wwebfor** [comment]
It was fixed by @ncpierson (currently it works in 0.7.2-RC2.

**Comment by trestletech** [comment]
Awesome! Thanks so much for your work on this.
