### ISSUE TITLE
Symbols like > sometimes get escaped and saved as &gt;, which ruins the markdown

### ISSUE THREAD

**Issue by zweicoder** [Laverna/laverna#368]
![image](https://cloud.githubusercontent.com/assets/3684550/12535406/31447882-c2bd-11e5-91e6-8f146e140b87.png)
As seen here

**Comment by tucker-m** [comment]
That's odd. I thought it *wasn't* escaping those characters, which is the problem in issue #345.

So, it should only escape < and > if those are inside of a code block. Does that sound about right?

**Comment by zweicoder** [comment]
Yeap, that's what I think should be the intended behavior. It's not consistent though and I haven't found out what really reproduces it, but at one point all of my quote blocks became regular > arrows
