### ISSUE TITLE
Sync issues with RemoteStorage

### ISSUE THREAD

**Issue by bnjbvr** [Laverna/laverna#377]
Hi,

I've been using Laverna with RemoteStorage sync for more than a month and I am quite happy so far :-)
I do see some synchronization issues sometimes, though:
- on computer A, I create a note x.
- on computer B, I sync, change content of note x and move it to another notebook.
- on computer A, note x's content hasn't changed, nor has it moved.

That's a bit annoying, because it also makes notes "reappear" from trash, etc. It's not a deal breaker though; I keep on using Laverna on the same machine and these problems don't happen, but that kinda breaks the spirit of sync :-)

Nothing weird seems to appear on the JavaScript developer console.
Please let me know if I can provide further information.
Cheers!

**Comment by wwebfor** [comment]
Yeah, it still needs to be improved. Currently we are working on improving encryption. We'll try to find out what's happening later.

**Comment by wwebfor** [comment]
Can the issue be closed? It seems like you fixed it :)

**Comment by bnjbvr** [comment]
I am a bit unsure about one thing: what happens when an object is completely deleted from machine A? I do think that if it's still live on machine B, machine B is going to re-create it (as it's not on the remote's storage backend), and I'd like to make sure this doesn't happen. Or I could open a different issue, only if needed :-)

**Comment by wwebfor** [comment]
You're right. We haven't tested the removal. I think if an object is removed, it is going to sync it with empty values. Because when an object is removed, the app makes all values of the item empty.

**Comment by wwebfor** [comment]
@bnjbvr we've just received bounty from 5apps for fixing bugs with RemoteStorage. Since you worked on fixing them too, we are eager to share that bounty with you. If you are interested, you can send us your Bitcoin address :)

**Comment by bnjbvr** [comment]
Nice, thank you! I've just sent you my bitcoin address to your email address mentioned on Github. Cheers!
