### ISSUE TITLE
Android based browser support?

### ISSUE THREAD

**Issue by nodje** [Laverna/laverna#40]
I can't get it to work under Android with Chrome or Firefox.

It should probably goes into Enhancement, but as no one as even mentioned it anywhere, and as it sounds so obvious to me, I'm wondering if it's not just my phone...or my server...

**Comment by wwebfor** [comment]
It seems like it works on Android now (at least on Firefox and Chrome). @nodje, if it doesn't work, please, feel free to re-open the issue.
