### ISSUE TITLE
Spell check

### ISSUE THREAD

**Issue by coworkingon-es** [Laverna/laverna#404]
Hi,
Is there a way to check spell in Laverna. Btw, love the tool!

Thanks!

**Comment by wwebfor** [comment]
Currently there isn't, but we're planning to add that functionality.

**Comment by coworkingon-es** [comment]
Ok, that would be wonderful, because I use Laverna for some sentence I copy and paste but if it would be a spell check, it would be a lot better! Thanks!

**Comment by ivangretsky** [comment]
I have installed local laverna and seems like this one is not implemented. Is it on the roadmap?

**Comment by Joey5460** [comment]
If Laverna can be compatible with some spell check add-on at web browsers, it would also be great.

**Comment by viniciusarcanjo** [comment]
+1. This feature would be highly appreciated.

**Comment by Ya5e** [comment]
+100 can we please get the feature? This is all thats holding me back from rating this app +10000

**Comment by wwebfor** [comment]
The feature now works in "dev" branch.
