### ISSUE TITLE
Inline code block `[]` causes html for a checkbox to show up

### ISSUE THREAD

**Issue by ncpierson** [Laverna/laverna#406]
The following markdown:

``` markdown
 If either side of the comparison can have `[]`, `""`, or `0` values...
```

Causes the empty array (in backtics) to expand into the html for a checkbox.

Example:

![laverna-bu](https://cloud.githubusercontent.com/assets/3130334/13363533/82939222-dc8f-11e5-8188-7e7216e4660b.png)

**Note: For anyone who also encounters this issue**, the temporary solution is putting two spaces inside of your inline array. No spaces or one space will cause the checkbox problem.

**Comment by wwebfor** [comment]
This issue was fixed in one of the RC releases.
