### ISSUE TITLE
encryption psw doesn't work

### ISSUE THREAD

**Issue by arcones** [Laverna/laverna#407]
hello, 

i have just set my encryption password and then when i try to open the app, it says "Encryption error" so i can't open any of my notes, please help!!

NB: i read some threads in this forum about similar problems but after cleaning local storage nothing seems to have improved, very frustated!!!

**Comment by wwwredfish** [comment]
What version of the app do you use?

**Comment by arcones** [comment]
Hello,


Thanks for the support, my version is desktop:

laverna-0.7.1-win32-x64

Regards

________________________________
De: wwwredfish <notifications@github.com>
Enviado: sábado, 27 de febrero de 2016 10:23
Para: Laverna/laverna
Cc: arcones
Asunto: Re: [laverna] encryption psw doesn't work (#407)


What version of the app do you use?

-

**Comment by wwwredfish** [comment]
Seems strange. I cannot reproduce this bug. Can you try to use a newer version of the app?

**Comment by arcones** [comment]
sorry for the delay

i've just downloaded the prerelease 0.7.2-RC3 (unique version which is newer that the one i had)
and the problem still remains
![captura](https://cloud.githubusercontent.com/assets/17352086/13612396/8d7a1dd8-e567-11e5-87fe-38857bcb5e16.PNG)

**Comment by bram1000** [comment]
Same issue using version 0.35.2 (laverna-0.7.1-win32-x64.zip).
Change encryption settings simply removes the encryption error window and doesn't do anything else, retry again just keeps bringing up the same issue again and again.

Funny how I'm locked out of my notes, not by forgetting my encryption password but by it failing to encrypt.

**Comment by bram1000** [comment]
A bit more info:
* This happened to me after I changed the encryption settings when I already had non encrypted notes.
* Going to localhost:9100 shows an empty list of notes, changing the encryption settings there works fine.

**Comment by funilrys** [comment]
Hi @nixpc @arcones,

Unfortunately, this issue will never be fixed here.

Please report to https://github.com/Laverna/laverna/issues/971#issuecomment-411423965 for the current state of this project and https://github.com/encryptic-team/encryptic for the future of this project.

Have a nice day/night.

Cheers,
Nissar
