### ISSUE TITLE
fs.exists is deprecated

### ISSUE THREAD

**Issue by greg-js** [Laverna/laverna#427]
I just discovered Laverna. I've been hoping for something to get me off Evernote for a while now and I'm especially excited about the recent [syncing to the file system commit](https://github.com/Laverna/laverna/commit/b2f3c677076dff64854ede2c13af26689eea1cac) because I would need this feature (and things built on top of it) before I can make the switch.

Anyway, I noticed that the code is making use of `fs.exists`, but that's been [deprecated](https://nodejs.org/api/fs.html#fs_fs_exists_path_callback) for a while now and the Node people have been talking about possibly removing it two major versions from now. So I would suggest replacing `exists` with something like the following helper to avoid having it break when/if it finally does get removed:

```
function isDirSync(pth) {
  try {
    return fs.statSync(pth).isDirectory();
  } catch (err) {
    if (err.code === 'ENOENT') {
      return false;
    } else {
      throw err;
    }
  }
}
```

or async:
```
function isDir(pth, cb) {
  return fs.stat(pth, function fsStat(err, stats) {
    if (err) {
      if (err.code === 'ENOENT') {
        return cb(null, false);
      } else {
        return cb(err);
      }
    }
    return cb(null, stats.isDirectory());
  });
}
```

Or [fs.access](https://nodejs.org/api/fs.html#fs_fs_access_path_mode_callback) (Sync) if you don't want to check specifically for a directory

**Comment by wwebfor** [comment]
Thanks for checking it out :)
