### ISSUE TITLE
Implement Tables

### ISSUE THREAD

**Issue by zauberparacelsus** [Laverna/laverna#439]
Would it be possible to implement the Tables functionality from extended markdown?  I am currently reviewing a few different note-taking applications, and table support is something that is crucial for my needs.

**Comment by wwebfor** [comment]
What do you mean by table support? Currently Markdown parser which we use supports table functionality. https://help.github.com/articles/organizing-information-with-tables/

**Comment by zauberparacelsus** [comment]
AFAIK, markdown doesn't/didn't have tables as a core feature.  I had already tried putting in tables using just the pipe characters, and it didn't work.  The requirement for putting in a row of hyphens was not something I had expected.
