### ISSUE TITLE
Images are not exported when downloading backup

### ISSUE THREAD

**Issue by F-A** [Laverna/laverna#449]
I tried download a backup of my notebooks (in settings "export data") but it seems the attached files are not exported or at least I could not find them in the compressed file.

**Comment by F-A** [comment]
The image also does not seem to be saved in the dropbox folder.
This is really annoying, especially in combination with the bug ["Note disappears when containing a reference to nonexisting"](https://github.com/Laverna/laverna/issues/414). All notes containing a file cannot be seen when synchronized on another computer.

**Comment by wweich** [comment]
This was also reported in #358 (last few comments)

**Comment by varod** [comment]
:+1:  synchronization of picture is for me a must have. Is it planned to integrate it in 0.7.3 ? 
I had to take notes in OneNote because of that ... do you imagine what hell it was for me? :) 
thanks

**Comment by wwebfor** [comment]
Fixed in "dev" branch.
