### ISSUE TITLE
Export encrypted notes in readable format

### ISSUE THREAD

**Issue by gVallverdu** [Laverna/laverna#454]
Hello!
I would like to know if there is a way to export notes in a readable format even if I use encryption. 
Actually, I would like to use encryption because I would like to keep my notes in a safe way. But I am a little bit afraid about loosing everything I wrote in laverna.

**Comment by wwebfor** [comment]
Hello.

If you export your notes from settings page, then they will be exported in decrypted format.

**Comment by gVallverdu** [comment]
Thanks
