### ISSUE TITLE
MathJax Setting Inverts Enable/Disable

### ISSUE THREAD

**Issue by johnblommers** [Laverna/laverna#455]
Noticed in Laverna 0.72-RC4, in Settings --> Modules --> MathJax

The sense of the enable/disable is reversed.

To enable MathJax you have to set it to Disable
To disable MathJax you have to set it to Enable

Observed for the OS X downloadable application.

$$  y=mx+b $$

The above is not rendered unless MathJax is disabled.

**Comment by Kamihimmel** [comment]
I think you misunderstood something.On the right is just the button to change status(To enable/disable it) but not the status now.
But I admit it is a bit confusing.It is better to show the status in font color(grey for disabled) and use a toggle not a button to change the setting.
Mathjax   [enabled]/disabled

**Comment by johnblommers** [comment]
Hello Kamihimmel, you are quite right. A clearly labeled on/off switch would clarify how the interface element is used.
