### ISSUE TITLE
App not usable - blank screen after dropbox auth

### ISSUE THREAD

**Issue by michaldybczak** [Laverna/laverna#457]
Laverna works great on browsers however when I tried app after giving login and pass to authenticate dropbox, I am asked to grant permission, hit window becomes white and nothing happens. When I close the window app asks me to authenticate again so I do and.. the same over and over.This happens on Manjaro Linux and Windows 10.

Login is successful, but it all happens when dropbox tries to gain access to a folder. Maybe I'm lacking of something? In both cases laverna wasn't installed and merely unzipped. If that's the problem, what should I do?

**Comment by wwebfor** [comment]
I think the issue was solved in one of the RC releases https://github.com/Laverna/laverna/releases

**Comment by michaldybczak** [comment]
The last release was 27 days ago, while my downloads were a week ago. The same bug on two very different systems points out that's not just an accidental and unique bug for me but a general defect that prevents from using this app.

**Comment by timbowman** [comment]
I ran into the same problem using 0.7.1. Tried again using 0.7.2-RC4 and authenticated Dropbox just fine.

**Comment by michaldybczak** [comment]
Where did you get 0.7.2-RC4 version. On github or laverna site there is still 0.7.1

**Comment by michaldybczak** [comment]
I installed 0.7.2-RC4 and it works now correctly. Github and official page still have 0.7.1 in downloads thou.
