### ISSUE TITLE
Some issues with checkboxes

### ISSUE THREAD

**Issue by romu70** [Laverna/laverna#461]
Hi,
First, I use Firefox only, don't know if this bug also occurs on other browsers. I've found few issues with checkboxes:

- the progress only works when checked boxes are adjacent. For example, check the 2 first boxes and the very end one, and this last check is not detected
- the progress is well saved when leaving the current note, but not the check marks. When you come back to this note with checkboxes, all boxes are unchecked.

Cheers.

**Comment by Kamihimmel** [comment]
I have the same thing but have a walkaround.
if you type a space between the brackets. the checkbox just works well.
Exp: [ ] get up at 7:00
but if you dont type space between the brackets.It will be buggy.
Exp:[] get up at 7:00

**Comment by wwebfor** [comment]
Hi,

Which version of the app do you use?

**Comment by romu70** [comment]
Personaly I connect through: https://laverna.cc/app/#notes
