### ISSUE TITLE
App not usable - blank screen after dropbox auth

### ISSUE THREAD

**Issue by forethoughtde** [Laverna/laverna#463]
I am have tried newest version on both Fedora 32-bit and iMac 64-bit. The problem is not solved. I have created a app in Dropbox, added redirect link and copied the API key. There is no success.

**Comment by arnaudbos** [comment]
Not sure but I think I have the same problem here:

Use the online app with dropbox sync so I can see the .json files into my Dropbox/Applications/Laverna folder.

Unfortunately when trying to sync with my OSX El Captain app, I import the settings file and get redirected to Dropbox where I authenticate and the popup window for Dropbox authentication just says blank.

**Comment by xelfe** [comment]
forethoughtde Did you try with the latest version 0.7.2-RC4 ? Because I had the same problem as you with the stable version 0.7.1.

**Comment by forethoughtde** [comment]
Yes. I did try with the latest version.

**Comment by johnblommers** [comment]
It **must** be 0.7.2-RC4 which is not the latest version, but only the most recent [Release Candidate](https://github.com/Laverna/laverna/releases). It absolutely fixes the Dropbox authentication problem on both OS X and on Linux.

**Comment by forethoughtde** [comment]
What is the most recent Release Candidate?

**Comment by claell** [comment]
0.7.2-RC4

**Comment by lukeasrodgers** [comment]
I just tried 0.7.2 and the issue appears to still exist. I get stuck at this screen:

<img width="625" alt="screen shot 2016-08-22 at 11 46 13 am" src="https://cloud.githubusercontent.com/assets/816444/17861206/1db20176-685e-11e6-82de-c70d29b0e08c.png">

OSX 10.10.5

**Comment by claell** [comment]
As far as I know the file structure changed with the update. So easiest way would be to look how the dropbox structure of the new version looks like and then adapt the already existing files (maybe with backup before).
