### ISSUE TITLE
Wikify Laverna

### ISSUE THREAD

**Issue by Pocc** [Laverna/laverna#474]
I would like to see linking to other notes. It's possible to get a noteID in evernote and in vimwiki, you enter [[a new file!]], escape insert mode, and hit enter, and you're already in the new file. Another way to go about it would be to have a link button on the top that asks you to search for a linking note.

Also, how do I mark this as an enhancement?

**Comment by wwebfor** [comment]
Actually there is a link button on the top where you can start searching a note by title or just place URL.

**Comment by Pocc** [comment]
This is an even better feature implementation than I had imagined. Great work!
