### ISSUE TITLE
Using OSX app with Dropbox sync fails

### ISSUE THREAD

**Issue by jakeparis** [Laverna/laverna#475]
There is no obvious **redirect_uri**, so the dropbox app authorization fails. In my dropbox app, I've set the oauth2 redirect uri to **https://laverna.cc/app/dropbox.html** and that works for the browser Laverna, but not the osx app.

**Comment by varod** [comment]
With desktop app, you should authorize `http://localhost:9000/dropbox.html` or `http://localhost:9100/dropbox.html`  depending the version. 
latest version seems to be on 9000.

**Comment by jakeparis** [comment]
I can verify that authorizing  `http://localhost:9000/dropbox.html` in the dropbox app makes the laverna desktop app sync up correctly. This should be added to the docs!
