### ISSUE TITLE
Need help on how to set Dropbox sync.

### ISSUE THREAD

**Issue by NoTalentGeek** [Laverna/laverna#484]
I have set the Dropbox API key in Laverna press Save but nothing happened.

![https://s31.postimg.org/43a4zcq0b/Image_012.png](https://s31.postimg.org/43a4zcq0b/Image_012.png)
![https://s31.postimg.org/x6ycvle3v/Image_013.png](https://s31.postimg.org/x6ycvle3v/Image_013.png)
![https://s31.postimg.org/pbntgs4h7/Image_011.png](https://s31.postimg.org/pbntgs4h7/Image_011.png)

Here are things those I have been set in both Evernote and Laverna. What should I do?

**Comment by NoTalentGeek** [comment]
Ooo. I pressed back button and then there is Dropbox authentication page appeared. But it shows this.

![https://s31.postimg.org/ault71vfv/Image_014.png](https://s31.postimg.org/ault71vfv/Image_014.png)

Settings are still the same like images in the first post.

**Comment by NoTalentGeek** [comment]
1. I got it fixed, it is a bit weird though.
2. So first I inputted my Dropbox API key and then press Save.
3. I pressed back button and then there is another window requests my Dropbox credentials.
4. However it went to `Error (400)`.
5. So what you should do is to go back to Sync setting and erase the Dropbox API key, press Save, and then press the Back button.
6. This will trigger the Dropbox login form without `Error (400)`.
7. After this the sync will be set.

**Comment by janis-kra** [comment]
Well, you got the error 400 because you did not specify any redirect URI on the settings page of your dropbox API key. But as the API key is optional anyway, you can setup dropbox sync completely without an API key. This results in the behavior that you described in 4.-6.

**Comment by danmichaelo** [comment]
@janis-kra 

> You got the error 400 because you did not specify any redirect URI on the settings page of your dropbox API key. But as the API key is optional anyway, you can setup dropbox sync completely without an API key. This results in the behavior that you described in 4.-6.

I cannot see a field for inputting a redirect URI. Has it been removed?

**Comment by janis-kra** [comment]
@danmichaelo it's in the app settings page just below the "App key" and "App secret" fields.

**Comment by Var-iazioni** [comment]
I got this problem too.
So what should I input in the redirect URL?
I try to input 'http://localhost', but it still '400'

**Comment by funilrys** [comment]
Hi @notalentgeek @danmichaelo @janis-kra @Var-iazioni 

Unfortunately, this issue will never be fixed here.

Please report to https://github.com/Laverna/laverna/issues/971#issuecomment-411423965 for the current state of this project and https://github.com/encryptic-team/encryptic for the future of this project.

Have a nice day/night.

Cheers,
Nissar
