### ISSUE TITLE
Cancel saves the Changes 

### ISSUE THREAD

**Issue by maxmopp** [Laverna/laverna#488]
expected: Cancel discards changes, Save saves changes
only works for new note, editing an old note: Cancel saves changes

**Comment by claell** [comment]
Plus when clicking cancel on a new note the note still will be created.

**Comment by NWuensche** [comment]
I will try to solve this bug. The problem is the auto save feature. It automatically saves after a few seconds, even if I click cancel afterwards. I will try to solve this by auto save in a tmp note, which will be deleted when you click cancel, but not if the program accidentally crashes.

**Comment by talklittle** [comment]
In addition, it would probably make sense to add a prompt to confirm cancellation when changes are detected.

Currently, thanks to auto save, if I am working on a note for a few hours, then accidentally hit Cancel, I don't lose anything.

If Cancel were to actually discard the changes, then that opens up an easy way to accidentally lose your work.

Ultimately I think the ideal solution would be the addition of Notes History (#125), and then it would make sense to eliminate the distinction between Save and Cancel.
