### ISSUE TITLE
Creating extra, bad tags 

### ISSUE THREAD

**Issue by warrensallen** [Laverna/laverna#493]
Loving this app so far, mostly. Looking to replace evernote... Having this issue with tags: when creating a tag in a note, I start typing the tag (e.g. #thisnewtag) and I often end up "accidentally" creating multiple tags like #th and #thisne  and #thisnewtag. They end up in the tag list and create an unmanageable amount of clutter.

![image](https://cloud.githubusercontent.com/assets/15705603/16661575/9387e6ae-4441-11e6-9309-0b4d9079bccc.png)

**Comment by joshterrill** [comment]
How do you even create tags? I'm using the latest version and don't see an option to do this.

**Comment by janis-kra** [comment]
@joshterrill you just write `#yourtaghere` somewhere inside your note (as opposed to `# heading` which creates a heading)

**Comment by joshterrill** [comment]
I think it would be much more user-friendly if there was a tags section on each document you create. Kind of like how evernote does it. That way you have one section to create and see all the tags rather than creating them in the body of the document where you type.
