### ISSUE TITLE
osx tray icon wrong size

### ISSUE THREAD

**Issue by luclu** [Laverna/laverna#497]
version `0.7.3`
![tray](https://cloud.githubusercontent.com/assets/10135872/16781128/0ef16d4c-487a-11e6-8744-2d9748b4b74a.jpg)

**Comment by kevinjcliao** [comment]
Can confirm also experiencing this on 0.7.3.

**Comment by Erfahrungen** [comment]
Same here.

![ohne titel](https://cloud.githubusercontent.com/assets/3730406/17173962/3fd8bdd6-53fe-11e6-9f74-f827b3692275.png)
