### ISSUE TITLE
'Command not found' Error for Gulp and Bower Solved, 'NPM Start' and 'Loading...' app Error

### ISSUE THREAD

**Issue by JerJohn15** [Laverna/laverna#504]
Hello Laverna team,

I had been following the instructions to "Installation from Source" step-by-step, and ran into a "command not found" error when running "bower install" and "gulp build". However, I was able to solve both of them by installing each one globally (see [bower solution](http://stackoverflow.com/questions/12369390/bower-command-not-found) and [gulp solution](http://stackoverflow.com/questions/22224831/no-command-gulp-found-after-installation)). I would like someone to verify both answers (I entered the exact commands before performing ``` bower install ``` and ```gulp build```).

If both are satisfactory, I would like to request that the documentation for the "Installation from Source" section be updated to reflect the changes mentioned in both solutions.

**Comment by wwebfor** [comment]
Yes, Bower and Gulp need to be installed globally.

**Comment by JerJohn15** [comment]
Okay, great! Now I have another question, @wwebfor  and community: I am trying to start this application using ```npm start``` and alternatively, ```node ./server.js``` after I run ```gulp build```, but neither commands appear to work (see image below). 

![laverna start error](https://cloud.githubusercontent.com/assets/6578161/16927023/7b87941c-4cf9-11e6-9935-dfaef3b5df78.png)

**Comment by wwebfor** [comment]
You can start by using `gulp` command (without any arguments).

**Comment by JerJohn15** [comment]
@wwebfor Okay, so I was able to get it to work with using the ```gulp``` command (_I like how it automatically connects me to the server within my browser_ ),  however, I am running into an issue with the webpage loading similar to #300. I get the following error message when inspecting the browser: 

Error Message | Code in Question | Line References| 
--------------|-------|------------------|----------------
Script error for "**markdown-it-imsize**", needed by: **modules/markdown/libs/markdown-it http://requirejs.orgt/docs/errors.html#scripterror** | ```makeError()``` |       require.js:168
|  | ```newContext/context.onScriptError()```  |     require.js:1735

![loading screen error](https://cloud.githubusercontent.com/assets/6578161/16990841/8d79c9a0-4e67-11e6-82c5-af29adad9186.png)

This does not occur when I navigate to laverna.cc or laverna.cc/nightly/. I'm using the current version if Firefox, 47.0. 

When I go to the [link](http://requirejs.org/docs/errors.html#scripterror) provided in the error message, it mentions that "usually... there is a JavaScript syntax error or other executing problem running the script". I'm not sure what this could be since I have not added any additional code to my forked copy. 

I'm going to look into this some more and update this answer should I make any progress.

**Comment by wwebfor** [comment]
Please, try to install markdown-it-imsize with a command:

```bash
bower install
```

**Comment by JerJohn15** [comment]
I finally managed to get this to work! That command did not work for me because I needed to provide [root access](http://stackoverflow.com/questions/22257726/eacces-error-with-bower-install) to bower ```markdown-it-imsize``` by running ```sudo bower install --allow -root``` as mentioned in the solution. I think there must have been an issue on my end with how I installed npm/node js, as I am not able to install most packages unless I provide ```sudo``` privileges. I am pretty sure that if I did have root access  ```bower install``` would have installed "markdown-it-imsize. I'm probably going to have to fix this at some point. Nevertheless, I'm glad I can finally start playing around with this project now.

**Comment by wwebfor** [comment]
It shouldn't require root access.

**Comment by JerJohn15** [comment]
@wwebfor  When I tried entering it as you suggested, this occurred:

(1) **Bower ACCES Error:**

![bower acces error](https://cloud.githubusercontent.com/assets/6578161/16995669/9a3c74f8-4e7b-11e6-908c-a8f8491dc764.png)

(2) So I tried to install it using the ```sudo``` command but I was presented with a message stating that sudo was not needed (like you had mentioned):

![bower sudo not needed](https://cloud.githubusercontent.com/assets/6578161/16995881/9b8a338a-4e7c-11e6-9091-821e641de37f.png)


(3) finally,  following the instructions from the SOF solution I mentioned above, I managed to install it using ```bower install --allow-root```:

![bower access given](https://cloud.githubusercontent.com/assets/6578161/16995703/cf113bdc-4e7b-11e6-8d0c-030eb6bb7a4b.png)

**Comment by wwebfor** [comment]
Glad to hear ;)
