### ISSUE TITLE
Android app don't import

### ISSUE THREAD

**Issue by Karyshur** [Laverna/laverna#521]
Hello. It is possible that this is not a bug in your application, and I just did not understand how it works, because using it the first day, but my sequence of actions is as follows:

1) I downloaded Laverna for Windows, install, connect to Dropbox, I created the first note
2) Download and install Laverna for Android
3) The Laverna for Android when you first start the Import button pressed

Then Laverna starts acting very strangely missing. Pressing the Import settings \ Import data system writes "The action is not supported in any application" (maybe that translated wrongly, I do not have English localization).

I somehow overlooked it or application error?

Android version 6.0.1

**Comment by wwebfor** [comment]
Hello,

You need some kind of file manager for Android.

**Comment by Karyshur** [comment]
I have it, but nevertheless android app is not working properly. At the same time, web-version of the start from my mobile everything is working fine.

**Comment by claell** [comment]
Look at #477 there is a file manager which works.

**Comment by Karyshur** [comment]
Yes, this work, thank you!
