### ISSUE TITLE
Portable version

### ISSUE THREAD

**Issue by shnbwmn** [Laverna/laverna#537]
Hi there

Are there any plans to make a portable version? I'd like to carry Laverna on my USB/external drive. What this entails is having the settings/program data saved to the program folder, and ideally leaving no trace on the host computer.

**Comment by wwebfor** [comment]
Hi there,

You can already use on a USB drive starting from this release: https://github.com/Laverna/laverna/releases/tag/0.7.4-RC1

In order to save your notes to the USB drive, you can specify the folder from command line interface:

```shell
./laverna --data-dir=../laverna-data
```

**Comment by shnbwmn** [comment]
Oh, that's very good news. Cheers!

**Comment by dan0xii** [comment]
> In order to save your notes to the USB drive, you can specify the folder from command line interface:
>
> ./laverna --data-dir=../laverna-data

Hello @wwebfor, how do you do this with the Android app?

**Comment by RoyiAvital** [comment]
@wwebfor , How can it work in Portable Mode in Windows?

**Comment by RoyiAvital** [comment]
I wrote this - https://github.com/Laverna/laverna/wiki/Portable-Mode.
I miss information for macOS and Windows.

Thank You.

**Comment by nmaas87** [comment]
@RoyiAvital You have to use an absolute path on windows.
```
.\laverna.exe --data-dir=D:\laverna-data
```

Or use the really ugly one on windows:
```
laverna.exe --data-dir=../../laverna-data
```
