### ISSUE TITLE
Trying to save a note with no title silently fails

### ISSUE THREAD

**Issue by janis-kra** [Laverna/laverna#540]
If you create a new note and do not enter a title, saving the note silently fails. This should (imo) either display an error message or just apply an auto-generated note title.

I really appreciate this project so I would like to contribute some code to it. I started to poke around in the codebase a bit and came up with a somehow decent solution (going for the auto-generated title approach), which you can review here if you want to: https://github.com/janis-kra/laverna/commit/5e09bb7355938bc19f42e43c0a96b66cf78057a6

I'll open a pull request if you think that this could be at least the basis for a solution for this issue.

**Comment by NWuensche** [comment]
Wouldn't it be better to not allow notes without a title at all? Maybe give the user a hint that he should type a title like it is done with the password at the login page.

**Comment by wwebfor** [comment]
Nice solution. Also, it would be awesome to pass the 'New-Note' string to i18next.

**Comment by NWuensche** [comment]
@janis-kra Because you asked: it would be nice if you could do a PR with the modification from @wwebfor .

**Comment by janis-kra** [comment]
Awesome, I'll tend to this within the next few days. Thanks for your feedback
