### ISSUE TITLE
Editor : do not override CTRL+T shortcut

### ISSUE THREAD

**Issue by guillaume-uH57J9** [Laverna/laverna#555]
laverna's editor maps the shortcut CTRL+T to tab/indentation increase. 
laverna should avoid using this shortcut because it conflict with a widespread browser shortcut. 

By doing so, it override the "New Tab" shortcut of many desktops browsers. 
An user trying to open new tabs with the keyboard is unexpectedly unable to do so.

**Comment by guillaume-uH57J9** [comment]
I've done a quick code search inside laverna's repository and was unable to find where this keyboard mapping is defined. Thus I've not send a pull request yet.

**Comment by NWuensche** [comment]
I'm sorry, but when I press Ctrl + T, a new Tab will open. Can you explain how your editor looks like and where you cursor is when you press Ctrl + T to change tabs?

**Comment by guillaume-uH57J9** [comment]
You're right, there's no such issue with laverna. Sorry for the confusion.
