### ISSUE TITLE
'ToDo List' Checkbox not being created using markdown 

### ISSUE THREAD

**Issue by JerJohn15** [Laverna/laverna#580]
There have been other related issues regarding the Task List feature, but I am having an issue with getting one rendered.  When I try to create one via markdown in my forked copy of the project, I instead get this result:

**Actual Results:**

A checkbox not being rendered (shown in preview mode)

![markdown  checkbox preview](https://cloud.githubusercontent.com/assets/6578161/17677306/3e97f7a0-6300-11e6-84fc-5165597999c7.png)

A checkbox not being rendered (shown in edit mode)

![markdown edit preview](https://cloud.githubusercontent.com/assets/6578161/17677310/42161b50-6300-11e6-80c4-bdf1f52378a1.png)

**Expected Results:**

A rendered checkbox in markdown:

```
//markdown code for an unchecked and checked checkbox
- [ ]
- [X] 
```
Go [here](https://github.com/blog/1375-task-lists-in-gfm-issues-pulls-comments) to see what a checkbox should look like with markdown applied to it:

This error applies to the laverna.cc/app version and my own forked version of the source code (Note: I'm running a fork of the latest revision as of the writing of this post. I also have not implemented any additional code of my own).

**Comment by wwebfor** [comment]
It's not a bug. It is intended behaviour. If braces don't have some text, it will not be considered as a task.

**Comment by JerJohn15** [comment]
@wwebfor Oh I see now. I wasn't aware that you could make them that way. Thanks. You can close this issue now. 

Example:

![todolist](https://cloud.githubusercontent.com/assets/6578161/17787118/c5b648d4-6555-11e6-8430-707e8edef233.png)
