### ISSUE TITLE
Tags: Allow more characters

### ISSUE THREAD

**Issue by danmichaelo** [Laverna/laverna#584]
Right now it seems like only something like `A-Za-z0-9` is allowed. If I type `#ål`, for instance, it is not recognized as a tag name.

Accented characters should definitely be supported, but in other apps I also regularly use dots and hyphens in tag names. And then there are other alphabets etc… Would be great if a tag name could include anything except spacing.

**Comment by NWuensche** [comment]
Which Laverna version do you use? In the current release this isn't fixed, but it should be fixed in the Github code. Try to build laverna from source and then you can use all Unicode characters as tags.

**Comment by danmichaelo** [comment]
Cool! I'm just using https://laverna.cc/app/

**Comment by NWuensche** [comment]
I think this can be closed
