### ISSUE TITLE
Notes disappeared.

### ISSUE THREAD

**Issue by czrcbl** [Laverna/laverna#604]
Hi,
Today when I opened the app, the welcome message appeared, asking if I wanted to import data, as if it was a fresh install and there was no notes on the app.
I am using the desktop app on linux. 
All my configs are on the defaults, no sync. I have searched for the program data on my user folder but I could not find it. The only laverna folder I found was under .cache and was empty.
Where is the default storage location?

**Comment by claell** [comment]
Problem solved?

**Comment by czrcbl** [comment]
Sorry, I forgot to comment, It turns out the problem might have been caused by the fact I had another instance o Laverna opened  in another desktop.
