### ISSUE TITLE
New Feature Request:: Code handler

### ISSUE THREAD

**Issue by vik0803** [Laverna/laverna#61]
If we place a code in the note then the current code handler isnt able to handle some of the data.

Possibly we might need to use a shortcode as something else that can be easily understand that all the rest of portion mentioned in the note is code. 

For Sample purpose I have added it in our public note.
https://laverna.cc/index.html
![image](https://cloud.githubusercontent.com/assets/5364224/2706327/6b615fb4-c48e-11e3-8738-a3fb3348665f.png)

![image](https://cloud.githubusercontent.com/assets/5364224/2706331/7eeebd88-c48e-11e3-8e67-054763d1c3ef.png)

**Comment by wwebfor** [comment]
Fixed.
