### ISSUE TITLE
Archlinux integration !

### ISSUE THREAD

**Issue by funilrys** [Laverna/laverna#614]
Hello,
Just for information I just created the package of Laverna on [AUR](https://wiki.archlinux.org/index.php/Arch_User_Repository) !
You can find it [here](https://aur.archlinux.org/packages/laverna/) or for arch user you can directly install it from `yaourt -S laverna`

Have a nice day & long life to Laverna ;) !

**Comment by wwebfor** [comment]
That's awesome! Thank you for creating the package ;)
