### ISSUE TITLE
Did I misunderstood the purpose of the app?

### ISSUE THREAD

**Issue by aminecmi** [Laverna/laverna#62]
I think I misunderstood the purpose of the app.
I was triying to replace every note taking app I use every day. 
I taught that when connecting to the app from my mobile, I was going to find every note I took.
I triend configuring the dropbox sync with my computer, and my phone, but it didn't work either.
Am I missing something? I was wrong about the purpose of laverna ?

**Comment by wwebfor** [comment]
Since version 0.6.x it is possible to provide your own app key from settings page.
