### ISSUE TITLE
request for tags id format specification

### ISSUE THREAD

**Issue by magowiz** [Laverna/laverna#628]
I'm still in the process to realize a working migration from evernote to laverna (as described here https://github.com/Laverna/laverna/issues/508 ) I noticed that notes and notebook ids are in UUID format so I was able to generate new valid ids for them, looking at current tags.json file in my laverna backup I noticed that tags ids are different , they are composed by digits only and hyphens to separe groups : 
21 - 30 - 10 - 19      ( 21 digits, hyphen, 30 digits,...... )

I would like to know which format is this and how can I create new ids (and so create new tags from evernote export) .

In general I think it could be useful if you can provide technical and/or development information about laverna.

**Comment by wwebfor** [comment]
Tags' IDs are generated in different format for one reason: to find them without decrypting and without having long indexes in IndexedDB. Basically every tag's name is hashed with SHA256 and used as ID.

**Comment by magowiz** [comment]
Hi wwebfor, 
thank you very much for your response : I also read in the code somewhere that sha256 algorithm could be involved, anyway I thought I was wrong since sha256sum generates a shorter and hexadecimal hash, while tags ID are longer and only composed by decimal digits. 
Do you generate those hashes in a particular manner or do you perform an hexadecimal to decimal conversion to the hash?

**Comment by wwebfor** [comment]
Let me show you: https://github.com/Laverna/laverna/blob/dev/app/scripts/models/Encryption.js#L82
