### ISSUE TITLE
tray icon is too big on mac

### ISSUE THREAD

**Issue by zhanglongqi** [Laverna/laverna#630]
![snip20160913_1](https://cloud.githubusercontent.com/assets/956693/18464343/11a9a0de-79c3-11e6-8571-621033858304.png)
The icon is too big on the 15.6.0 Darwin

**Comment by ryanbaer** [comment]
I actually fixed this: https://github.com/Laverna/laverna/pull/558

However, it seems there hasn't been a new release / pre-release since it was merged in. Not sure how technical you are, but if you build from source, it has the correctly sized icon with retina / dark mode support.

**Comment by zhanglongqi** [comment]
Yes. I tried. It looks nice.
![snip20161025_23](https://cloud.githubusercontent.com/assets/956693/19669282/af5b2a3a-9a90-11e6-96ed-395f623c7b71.png)
