### ISSUE TITLE
Can notes be shared 

### ISSUE THREAD

**Issue by fredhampton** [Laverna/laverna#652]
Is it possible to share notes ?

**Comment by wwebfor** [comment]
For now they cannot be shared.

**Comment by jekuno** [comment]
Maybe we should add this to a FAQ and close this (and other) issues to shorten the issue list a little bit?

**Comment by grand-lotus-iroh** [comment]
+1 for note share / export capabilities. even if a public dropbox link is able to be copy / pasted to clipboard automatically after using a hotkey to share note.

**Comment by devurandom** [comment]
This is somewhat a duplicate of #198.

**Comment by funilrys** [comment]
Hi @fredhampton @devurandom @grand-lotus-iroh @jekuno,

Unfortunately, this issue will never be fixed here.

Please report to https://github.com/Laverna/laverna/issues/971#issuecomment-411423965 for the current state of this project and https://github.com/encryptic-team/encryptic for the future of this project.

Have a nice day/night.

Cheers,
Nissar
