### ISSUE TITLE
Night Mode

### ISSUE THREAD

**Issue by JonthueM** [Laverna/laverna#656]
Can you change the skin to night mode? is there a way to style it? CSS?

**Comment by twardakm** [comment]
Hello!
I know it's old topic, but I see a lot of people have a similar [issue](https://github.com/Laverna/laverna/issues/421).

I found a partial solution. I mostly use the Laverna as a web application and recently I started to use [**Care your eyes**](https://chrome.google.com/webstore/detail/care-your-eyes/fidmpnedniahpnkeomejhnepmbdamlhl) add-on. Basically it makes every website dark and Laverna looks amazing with this add-on!
