### ISSUE TITLE
[correction]How-to says tags are created with @

### ISSUE THREAD

**Issue by jfml** [Laverna/laverna#663]
Hello, just a small thing (maybe I don't get it) but the How-to („How to use tags and tasks“) on the Webapp states that tags are created with @ (which does nothing for me) while the [FAQ](https://github.com/Laverna/laverna/wiki/FAQ) says tags are done with # (which works for me).

Thanks for the good work!

**Comment by ghost** [comment]
I think this has been solved. We can close the issue.

**Comment by jfml** [comment]
Can't find the How-to in the web-app, so you're probably right ^__^
