### ISSUE TITLE
Text stats

### ISSUE THREAD

**Issue by avently** [Laverna/laverna#665]
Hello. Can you make a plugin or something that can show text stats?  I mean something like:
210 words
2004 characters
232 characters per minute

It can show up on the top/bottom of the right corner, for example. 

I think this would be useful for many people that work with text by their profession.

**Comment by wwebfor** [comment]
Implemented in https://github.com/Laverna/laverna/commit/c6780aad821a3129abab9b1dc524bd7fcd82f6b8

Except for "characters per minute" feature.

**Comment by avently** [comment]
@wwebfor thank you!
