### ISSUE TITLE
purpose of dev branch is unclear

### ISSUE THREAD

**Issue by mattpalermo** [Laverna/laverna#682]
The [README](https://github.com/Laverna/laverna#coding-style-guidelines) is clear:

> all experimental changes are being pushed on the dev branch, so any feature changes are preferred to be done on either this branch or a branch that uses the dev branch as its parent.

But looking at the commit history, it seems that this is not happening and the dev branch is being left behind (currently only 35 commits behind). This is a bit confusing, should I branch off from master or dev?

**Comment by wwebfor** [comment]
You should definitely branch off from dev.
