### ISSUE TITLE
issue importing settings and data ANDROID

### ISSUE THREAD

**Issue by capon3** [Laverna/laverna#691]
So, I installed 1 month ago the 0.7.4-RC1 android-armv7-release.apk to my android phone.

I had no issues! Was working perfectly. Pleased. Had to re-install all apps as I had reset my phone. 

When I reinstalled Laverna I followed the same process. Pretty simple. Except now when I go to import anything (data or settings) I get a pop up that says "CHOOSE AN ACTION - No apps can perform this action" 

Pretty frustrating, any ideas why that may be? 

Thanks in advance for any feedback you guys can give me.

**Comment by leolivier** [comment]
Almost same for me. 
The choose action proposes 2 applications on my LG G4: FM Radio (!!!) and File Manager but when I choose the file manager, it seems to open in a weird write mode (opened at root directory with only an "add button" and no files/directories shown so no way to navigate in the files and find the laverna-settings.json file)

**Comment by capon3** [comment]
Hmm, which file manager application do you have?

**Comment by leolivier** [comment]
Hi capon3,
On my LG G4, I have several file managers installed (including ES 
Explorer) but the only one that is proposed in the application is the 
standard Android (or LG?) pre installed one simply dubbed "Files 
Manager" (actually "Gest. Fichiers" in French)

**Comment by leveled** [comment]
Ive been having the same issue as well on Nexus 6p with Cyanogenmod 14 installed. I've tried Amaze and ES file explorer and they both weren't recognized

**Comment by claell** [comment]
There already are several issues about this. And there seems to be one file manager that works (is listed in one of the issues)

**Comment by capon3** [comment]
Which one?

Thanks

**Comment by leolivier** [comment]
Found something in [issue 477](https://github.com/Laverna/laverna/issues/477) :  fdroid would be the solution, not yet tested

**Comment by leolivier** [comment]
I confirm that OI File Manager does the trick !

**Comment by capon3** [comment]
Sweet! I too confirm. OI File Manager from F-Droid has don't the trick.

Thanks guys!
