### ISSUE TITLE
tagging posts with Laverna on Mac OS X

### ISSUE THREAD

**Issue by yarden** [Laverna/laverna#715]
I read that it's possible to tag posts with Laverna by just using ``@tagName`` in post body. However, when I try this, it doesn't appear to register as a tag and I don't see a way to browse posts by tag in the UI. It would be incredibly useful to have this basic feature -- i.e., be able to tag posts and then show all the posts that have a particular tag from the main app's menu. Is this possible with the current version? I'm using  ``laverna-0.7.4-RC1-darwin-x64``. Thanks.

**Comment by yarden** [comment]
Sorry, it works if I use ``#tagName``, but I still don't see a way to show all the tags in the app's menu.

**Comment by klarani** [comment]
You can find them if you open "notebooks" in the menu... I added a usability-issue with this one included too :)

https://github.com/Laverna/laverna/issues/718

**Comment by yarden** [comment]
Nice, I completely missed that, thank you.
