### ISSUE TITLE
Where are the notes stored? Lost my notes after 0.7.4 upgrade.

### ISSUE THREAD

**Issue by jastuccio** [Laverna/laverna#723]
Just now I upgraded to Laverna 0.7.4 to resolve a bug sinking with Dropbox.  I was not able to sync with dropbox prior to upgrading.  Now my notes are not showing up.  I have full backups, but do not know where to get the existing notes.  I do not see a `laverna` folder under `~.config/laverna`

**Comment by jastuccio** [comment]
@funilrys I am in OSX 10.12.2 and just resolved this.

After posting I came up with an idea that resolved this.  I restored Laverna to 0.7.1 from this morning. Exported the notes, imported them into 0.7.4 They are now also in Dropbox.

**Comment by funilrys** [comment]
So we can close this then ?

**Comment by jastuccio** [comment]
Yes it can be closed.  Thank you.

**Comment by simongray** [comment]
Had the same issue upgrading from the same version on Mac OS. Used the same solution as @jastuccio

**Comment by funilrys** [comment]
@wwebfor We should mark this as bug...

**Comment by funilrys** [comment]
@wwebfor @jastuccio  please close this.
