### ISSUE TITLE
[Ubuntu] Encryption error - How to remove all traces of Laverna and install again?

### ISSUE THREAD

**Issue by matt32106** [Laverna/laverna#724]
I have messed up the configuration of Laverna on the second machine on which i installed it.

Now when i launch it and enter the crypto key it says "Encryption error" 

I would like to start from scratch but if i only delete the unzipped laverna directory and unzip again the install file, i still get the encryption error.

Is there a way to reset completely?

**Comment by funilrys** [comment]
Did you execute `sudo apt-get autoclean` ? ([Source1](http://askubuntu.com/questions/3167/what-is-difference-between-the-options-autoclean-autoremove-and-clean)|[Source2](http://www.stchman.com/cleanup.html))

**Comment by matt32106** [comment]
IF there was an apt-get package i would have but this not the case
> sudo apt install laverna
> E: Unable to locate package laverna

I unzipped the download file to install and i launch the bin file to run it.

**Comment by funilrys** [comment]
My bad sorry @matt32106, I'm an Arch User :smile_cat: ...

But you still use a Linux distribution so I think you can at anytime delete the directory `~/.config/laverna/` which result of what you want to do.

**Comment by matt32106** [comment]
Strange, i had no ~/.config/laverna/ directory. 
Anyway, i solved my problem by locating and deleting all dirs and files containing "laverna". 
That did the trick.

**Comment by funilrys** [comment]
@matt32106 that's because electron use chromium... But it still strange that Ubuntu create those directory ...
