### ISSUE TITLE
how to recover images from laverna export?

### ISSUE THREAD

**Issue by yarden** [Laverna/laverna#736]
I have some notes that contain images in them in my laverna notebook. When I export the notebook to my hard disk, the notes are serialized as .json and .md files in ``notes-db/notes/``:

```
$ ls notes-db/notes
2928ad3e-72dc-c8a2-26bc-669dd5640224.json
2928ad3e-72dc-c8a2-26bc-669dd5640224.md
```
But I don't see the image file anywhere. I'm using encryption: does that change perhaps where, or if, the image is stored as well?

Thanks.

**Comment by F-A** [comment]
AFAIK, the images are not exported, see issue #449

**Comment by wwebfor** [comment]
Fixed in "dev" branch.
