### ISSUE TITLE
Outdated SSL certificate on website

### ISSUE THREAD

**Issue by InviteCiel** [Laverna/laverna#742]
Browser is now complaining on https://laverna.cc/ outdated SSL cert.
Please check your Certbot configuration, and check why it hasn't been updated automatically.

**Comment by cleac** [comment]
:+1: can't use the app due to this problem :-( Can anybody fix this?

**Comment by InviteCiel** [comment]
Only domain/server owner could fix this issue due to the need of access to server configuration.
I would strongly suggest that owners fix or configure automatic certificate renewal so there is no need to remember about SSL certs ever again.

BTW, see [Certbot user guide](https://certbot.eff.org/docs/using.html) to figure out how to use Certbot's auto renewal.

**Comment by wwebfor** [comment]
It happened because the cron-job didn't reload the server. It was fixed now.
