### ISSUE TITLE
Images does not get displayed when I "import data"

### ISSUE THREAD

**Issue by skashish** [Laverna/laverna#756]
Hi,
I am using laverna-0.7.1-linux-x64 on ubuntu.
I had to reinstall ubuntu, So, I went to settings -> Export data.
Afterwards, when I imported data, all the text in the notes came back but the images disappeared.

Why doesn't laverna backup the images? or does it?

**Comment by F-A** [comment]
AFAIK, the images are not exported, see #449

**Comment by kiamgrebgnur** [comment]
Same here, when will this be supported ?

**Comment by F-A** [comment]
I haven't looked at the code recently, but as far as I understood when reporting the bug one year ago, the attachments where not referenced in the database.
It might therefore need a major refactoring of the code to fix this. And you would need to go through all existing notebooks, looking for attachment to reference them in the database when updating Laverna.

**Comment by wwebfor** [comment]
It was fixed in "dev" branch.

**Comment by skashish** [comment]
hi @wwebfor 
As of today, I downloaded laverna-0.7.51-linux-x64 from https://laverna.cc/#download
and I can confirm that this doesn't work on that.

If that's really fixed, Please consider updating binaries on website as not everyone has the time to build it from source.
