### ISSUE TITLE
TAGS in non-latin

### ISSUE THREAD

**Issue by dayfuaim** [Laverna/laverna#762]
TAGS in non-latin, in my case it's Cyrillic, don't work.
I.e. `#work` works, but `#работа` or `#Работа` don't.

I use Ubuntu 17.04, Laverna 0.7.3.
Android 0.7.4 version does the same.

Please, fix this.

P.S.: All the rest is working just perfect.

**Comment by dayfuaim** [comment]
Is developer *still* here?
Problem **will be** persisting until fixed.

Please, fix it.

**Comment by wwebfor** [comment]
Thank you for reporting the issue. The bug was fixed in "dev" branch.
