### ISSUE TITLE
Old version of Dropbox platform is being retired

### ISSUE THREAD

**Issue by acohan** [Laverna/laverna#776]
I just noticed this warning when connecting Laverna to my dropbox. 

> The old version of the Dropbox platform is being retired on June 28, 2017. The developer of this app has yet to acknowledge the change, so this app may not continue to work in the future.

**Comment by kadomcevi** [comment]
Linux Gentoo 64bit.  I can't connect to dropbox account, all buttons in registration form come inactive.

**Comment by benmordecai** [comment]
I got the same message as @acohan from Chromium on Linux Mint.

**Comment by funilrys** [comment]
All the dropbox part have to be rewritten ...

**Comment by k00lagin** [comment]
I have the same problem as @kadomcevi on Win10

**Comment by benmordecai** [comment]
Is this project still in active development?

**Comment by talklittle** [comment]
@benmordecai Yes it is clearly under active development: https://github.com/Laverna/laverna/commits/dev

There is a recent issue #778 that appears to be a way forward: peer-to-peer syncing via a self-hosted "signaling server" (no data stored on server), without depending on services like Dropbox anymore.

**Comment by teknogeek** [comment]
Mine says the same, but a later date.
>The old version of the Dropbox platform is being retired on September 28, 2017. The developer of this app has yet to acknowledge the change, so this app may not continue to work in the future.

**Comment by mslipper** [comment]
Ditto here - just received an e-mail from DropBox warning me about these changes.

**Comment by submarine89** [comment]
Just received one as well.

**Comment by claell** [comment]
If this is not adapted to the new Dropbox API, Laverna will become useless for me.

**Comment by wwebfor** [comment]
Fixed.
