### ISSUE TITLE
Feature Request: Cross Page Linking

### ISSUE THREAD

**Issue by CMCDragonkai** [Laverna/laverna#78]
Would be great if Laverna supported cross page linking. Now I know it's a web app, so there are "hyperlinks", but something relative that doesn't rely on absolute links would be cool.

Maybe even a specific app related protocol like: `laverna://...etc`. Which would allow other apps to link to things on Laverna!

**Comment by claell** [comment]
I guess this is an duplicate, right?

**Comment by wwebfor** [comment]
I think it is a duplicate of #252. So closing.
