### ISSUE TITLE
Tags are recognized only in English.

### ISSUE THREAD

**Issue by AndreWin** [Laverna/laverna#782]
Hello!

Text like `#project` will be recognized as tag. Text like `#проект` willn't be recognized as tag. It seems for me it's so because `#проект` isn't on English but on Russian lang.

Please make laverna to recognize tags on other langs.

Best regards, Andrey.

**Comment by dayfuaim** [comment]
Я уже писал об этом (I already wrote about it): https://github.com/Laverna/laverna/issues/762
Hope that developer won't drop this cool project.

**Comment by wwebfor** [comment]
It works in "dev" branch and will be available in the future.
