### ISSUE TITLE
Fix Portuguese translation

### ISSUE THREAD

**Issue by gusbemacbe** [Laverna/laverna#785]
Hey @wwebfor,

You did a small bad translation:

You put:

```
    "pt_br": {
        "name": "Portugisch (Brasilien)",
        "nativeName": "Portugisch (Brasilien)"
    },
```

I fixed instead:

 ```
   "pt_br": {
        "name": "Portuguese (Brazil)",
        "nativeName": "Português (Brasil)"
    },
```

And a Brazilian translator forgot of switching from Windows ISO to UTF-8 for the file Brazilian Portuguese translation.json 
because before, it appeared with dirty characters in Laverna when you switched to Portuguese. 

I am going to drop two files for you: [Brazilian Portuguese and Locales](https://github.com/Laverna/laverna/files/1149872/Portuguese.zip)

**Comment by funilrys** [comment]
Hi @gusbemacbe 

Unfortunately, this issue will never be fixed here.

Please report to https://github.com/Laverna/laverna/issues/971#issuecomment-411423965 for the current state of this project and https://github.com/encryptic-team/encryptic for the future of this project.

Have a nice day/night.

Cheers,
Nissar

**Comment by gusbemacbe** [comment]
It is why I closed the issue as Laverna is shut down according to Alternativesto

**Comment by daed** [comment]
@gusbemacbe FYI, I am integrating your changes into Encryptic, which is forked from Laverna.

**Comment by gusbemacbe** [comment]
@daed 

I was not aware that Laverna has been merged into Encryptic. Thank you for notifying me about Encryptic!
