### ISSUE TITLE
Evernote to Laverna

### ISSUE THREAD

**Issue by Dav48** [Laverna/laverna#819]
How can I import my evernote notes to Laverna?

**Comment by wwebfor** [comment]
You can export from Evernote to .enex backup file like described [here](https://help.evernote.com/hc/en-us/articles/209005557-How-to-back-up-export-and-restore-import-notes-and-notebooks).

After that, you can import that file using the feature implemented in "dev" branch.. It will be available in the next release and look like this:

![screen shot 2018-01-16 at 15 58 13-fullpage](https://user-images.githubusercontent.com/2404615/34982890-f6d1eb5a-fad5-11e7-84e1-b82bc88546ad.png)
