### ISSUE TITLE
Dropbox sync is broken

### ISSUE THREAD

**Issue by Balur86** [Laverna/laverna#841]
Hello,

I can sync nothing to my Dropbox. Is it something related with yesterday's Dropbox API change? Anyone notice the same or just me?

**Comment by ViSo1o** [comment]
I also have this error. Can't sinc app on linux and app on the tablet

**Comment by talklittle** [comment]
Developer is working on it.

Duplicate of #805

**Comment by wwebfor** [comment]
I think it was fixed in 0.7.5 release.
