### ISSUE TITLE
0.75：Programs crash when opening

### ISSUE THREAD

**Issue by stonedreamforest** [Laverna/laverna#842]
windows10  x64 14193

https://github.com/Laverna/laverna/releases/download/0.7.5/laverna-0.7.5-win32-x64.zip

https://github.com/Laverna/laverna/releases/download/0.7.5/laverna-0.7.5-win32-ia32.zip

**Comment by zboraon** [comment]
Same in Linux Mint 18.2

**Comment by funilrys** [comment]
@zboraon any logs when executing from terminal ?

**Comment by zboraon** [comment]
@funilrys 
says:
`Segmentation fault`

**Comment by dayfuaim** [comment]
Same in macOS 10.12.6.
```
Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [0]

VM Regions Near 0:
--> 
    __TEXT                 000000010386c000-000000010386d000 [    4K] r-x/rwx SM=COW  /Applications/laverna.app/Contents/MacOS/Electron
```

**Comment by M-O-Z-G** [comment]
Same on Windows 7 x64

**Comment by funilrys** [comment]
@wwebfor I personally tested it over Arch 32 bits (yes it still exist :wink: ) and Arch 64 bits and even after deleting  the `~/.config/laverna` directory I still get `Segmentation fault (core dumped)`. So if there is arch user here, you have to wait a bit for the update!

However, when running the procedure of the **[Installation from source](https://github.com/Laverna/laverna#installation-from-source)** Laverna is started into the browser without any issue.

So, it looks like an electron issue ...

**Comment by wwebfor** [comment]
@funilrys, yes, there was an issue with it.

**Comment by funilrys** [comment]
:+1:  Arch Linux version updated :white_check_mark: !!

**Comment by johnblommers** [comment]
On OS X El Capitan Laverna-0.7.51-darwin is working great again. Thanks much for fixing her up.
