### ISSUE TITLE
Incorrect parsing of code/preformatted text in check lists

### ISSUE THREAD

**Issue by TheDcoder** [Laverna/laverna#850]
The check list/task list ends if a `pre-formatted text` is encountered. Tested with Laverna `v0.7.51`, here is an example:
![image](https://user-images.githubusercontent.com/6347576/31351032-2771f192-ad47-11e7-8036-513d2bef833d.png)
```
- [x] Incorrect parsing of code/preformatted `text` in check lists
```

**Comment by dayfuaim** [comment]
I have already posted an issue #787 about this (and not only). :)
But there's still silence here on that.

**Comment by TheDcoder** [comment]
Oh, I didn't notice your issue when searching for similar ones. I hope the developers fix this soon, it's very annoying

**Comment by TheDcoder** [comment]
Thanks for fixing the issue!
