### ISSUE TITLE
Dropbox syncing error

### ISSUE THREAD

**Issue by Garrettlynch** [Laverna/laverna#856]
I'm getting dropbox syncing errors in the self hosted web app.  I've set up Dropbox app with redirect uri, connected Laverna so no 400 error and when I try to sync I get this in the console:

main.js:1114 Dropbox error t {method: "GET", url: "https://api6.dropbox.com/1/metadata/auto/notes-db/…4BQya5EAW2DFWP1iE&include_deleted=false&list=true", status: 400, responseText: "{"error": "v1_retired"}", response: Object}

My drop app folder is there but no files appear.

**Comment by rodu** [comment]
I am getting the same error and it appears that the Dropbox API v1 that probably Laverna is using has been deprecated on the Dropbox side. See this announcement: https://blogs.dropbox.com/developers/2016/06/api-v1-deprecated/

**Comment by Garrettlynch** [comment]
Yes, searching the error message and looking at Laverna's code yesterday discovered that it is using v1 of the Dropbox api.  The swap over looks quite painful when I looked into it so holding off a week or so to see if it gets updated but Dropbox did announce this quite a while back so not very hopeful that Laverna will be fixed.

**Comment by e-volusian** [comment]
@Garrettlynch what version are you using? according to [this commit](https://github.com/Laverna/laverna/commit/a619d2741e4ffdcd34fdee045ed97497ae0ac10b) from 25 days ago, it looks like Laverna should have Dropbox v2 support on versions 0.7.51 +   

Even with that being the case and using the latest version, I still have the same error...

**Comment by Garrettlynch** [comment]
It was 0.7.3.  Downloaded the static web based version again this morning and it's now at 0.7.51 so has now caught up with the source code/apps.  Tested and all seems to be working well with Dropbox.
