### ISSUE TITLE
Cannot Connect to Laverna.cc

### ISSUE THREAD

**Issue by zonegrave** [Laverna/laverna#865]
I am having trouble visiting 'laverna.cc', it says "Not found :(", which also causes my laverna app cannot link to the Dropbox app.
I think it is because "https://laverna.cc/app/" is in the Redirect URIs.
Is it just me who's facing this problem?
Will the website be closed permanently?

**Comment by alsacefan** [comment]
I am having the same issue.

**Comment by threkk** [comment]
Same here, it has been down since early this morning on CET.

**Comment by funilrys** [comment]
It looks like a firewall or a misconfiguration as no HTTP Status code is returned ...

**Comment by funilrys** [comment]
It looks like a firewall or a misconfiguration as no HTTP Status code is returned ... I don't know the backend but that's my opinion... 

Can you confirm/fix @wwebfor ?

**Comment by veloute** [comment]
Seems to be back up now.

**Comment by funilrys** [comment]
:+1:

Please close @zonegrave || @wwebfor :smile_cat:

**Comment by luisca-dev** [comment]
having the same problem
