### ISSUE TITLE
Confirmation Dialog HTML Parsing Error

### ISSUE THREAD

**Issue by chrunchyjesus** [Laverna/laverna#882]
The confirmation dialog for deleting a notebook does not parse the HTML Markup properly.

![image](https://user-images.githubusercontent.com/20382692/33794610-40dc18da-dccf-11e7-9d1a-ceb8e1d0877a.png)

**Comment by wwebfor** [comment]
It's been fixed in "dev" branch.

**Comment by chrunchyjesus** [comment]
Thanks for your work. :)
