### ISSUE TITLE
Typo in welcome message

### ISSUE THREAD

**Issue by dinosw** [Laverna/laverna#885]
Hi, I have noticed a typo in the welcome message. I have highlighted it in the screenshot below.
![image](https://user-images.githubusercontent.com/7477309/34257732-59681c6a-e65b-11e7-92d5-f5bc07740de2.png)

Kind Regards and Merry Christmas
Steven

**Comment by wwebfor** [comment]
Thanks for reporting the issue and Merry Christmas.
