### ISSUE TITLE
Signal server error #405

### ISSUE THREAD

**Issue by KenrySanchez** [Laverna/laverna#892]
Hello, guys. I'm trying to use Laverna for dev develop and after I type my new password as a new user, it sends me this error. What does it mean??

`Signal server error #405
`

**Comment by wwebfor** [comment]
It means that the signal server is not up and running. For now, we don't have a public signal server. You need to start this on your computer: https://github.com/Laverna/laverna-server

**Comment by KenrySanchez** [comment]
thanks a lot @wwebfor
