### ISSUE TITLE
Click a link resulting in "NOT FOUND" Page 

### ISSUE THREAD

**Issue by mru4913** [Laverna/laverna#909]
Try to write the following,

[reference to a repository file](/Users/...../......)

I accidentally typed the wrong path. Once I click the link, it leads me to a "not found" page, which is reasonable so far.

BUT I cannot go back to the main notebook page. Is there a way to go back instead of restarting the program?

**Comment by funilrys** [comment]
Hi @mru4913 

Unfortunately, this issue will never be fixed here.

Please report to https://github.com/Laverna/laverna/issues/971#issuecomment-411423965 for the current state of this project and https://github.com/encryptic-team/encryptic for the future of this project.

Have a nice day/night.

Cheers,
Nissar
