### ISSUE TITLE
Is https://laverna.cc/ still running?

### ISSUE THREAD

**Issue by sharp-tasting** [Laverna/laverna#938]
It refuse my connections, thus only https://laverna.github.io/static-laverna/ works for me now. 
Do you have the same problem?

**Comment by funilrys** [comment]
@wwebfor I can confirm this. Please stage issues posting and take the time for issue triage ... 404 issues are huge and quite impossible to manage alone ...

**Comment by igorsantos07** [comment]
I guess that alternative domain is what's used by the electron app as well? Because it's working fine. I guess Laverna doesn't make any API calls, as it stores everything on our own cloud providers?

**Comment by sharp-tasting** [comment]
It's up and running again. Thanks for the maintainer.
