### ISSUE TITLE
linux laverna can not switch input method 

### ISSUE THREAD

**Issue by woodneko** [Laverna/laverna#940]
laverna 0.7.51 
system 16.04.1-Ubuntu
using fcitx with sogoupinyin input

**Comment by woodneko** [comment]
fcitx only can run with a normal user, I use root user running the laverna.
but if I running as a normal user the reomtestorage cannot sync client data to cloud server

**Comment by funilrys** [comment]
is this not a permission issue ? :thinking:

**Comment by woodneko** [comment]
@funilrys with normal user I can use fcitx switch input method but can not sync local note to cloud with remotestorage. The normal user have network permission I can catch the packages on both server and client with tcpdump

**Comment by woodneko** [comment]
this is a permission issue, the sync problem is solved with the network setting
