### ISSUE TITLE
Doesnt work correctly under iOS.

### ISSUE THREAD

**Issue by SolidNerd** [Laverna/laverna#95]
Hey i tested it on my iPad and with the native Safari and installed Chrome , i got on both devices these Error.

![sarfari-ios](https://cloud.githubusercontent.com/assets/886383/3138719/954e46cc-e8a9-11e3-93c8-45e84b2ab345.PNG)
![chrome-ios](https://cloud.githubusercontent.com/assets/886383/3138720/954e8d76-e8a9-11e3-8151-00ce944d3647.PNG)

**Comment by nlitsme** [comment]
maybe this is a problem with safari based browsers, i can't use laverna both on my mac and on my iphone.

in the error console on my mac i see this message:

NotFoundError: DOM IDBDatabase Exception 8: An operation failed because the requested database object could not be found.  main.js:9:11821

**Comment by wwebfor** [comment]
The issue was resolved.
