### ISSUE TITLE
Forgot password and using desktop version of Laverna

### ISSUE THREAD

**Issue by GeVic** [Laverna/laverna#956]
The issues is pretty clear from the title. I can't start over because the information is really important. Can I somehow retrieve the password of reset it?

**Comment by ghost** [comment]
unfortunately no, you need to guess/remember the correct password. If you have been using Laverna with the browser version you might be able to find your password in the browser history: #435 

Related issues: #218 #371

**Comment by GeVic** [comment]
Fortunately, I remembered my password. But I guess there should be a way around that. Shouldn't?

**Comment by ghost** [comment]
If there was, everyone would be able to access your notes. My recommendation is to use a very simple password that you cannot forget.

**Comment by ghost** [comment]
@GeVic, 

I added a new issue, what do you think about this idea: #957 ?
