### ISSUE TITLE
Error on opening

### ISSUE THREAD

**Issue by shreyashah115** [Laverna/laverna#958]
Right after installing and opening, getting this error. [macOS]

![image](https://user-images.githubusercontent.com/17617465/42272747-c8f4d752-7fa4-11e8-82e9-9b664cae8f30.png)

**Comment by daed** [comment]
It looks like something else is already using port 9000.  Especially with the "Cannot GET /" in the window.  Sounds like a non-http connection on the other side.

**Comment by daed** [comment]
From the terminal, you can use ```lsof -nP +c 15 | grep LISTEN``` to find out what is using which port.  Scroll through the right hand column and look for something like 127.0.0.1:9000, then check the process name on the left hand side.  You'll need to shut whatever it is down before you can run laverna.

Alternatively, you can change the port numbers for laverna, but I'm not too sure how to do that yet.

Source for command:  https://wilsonmar.github.io/ports-open/

**Comment by shreyashah115** [comment]
Thanks for responding!
