### ISSUE TITLE
Blankspace Support? Front Support?

### ISSUE THREAD

**Issue by roaming-debug** [Laverna/laverna#965]
Well, when I type blankspace in front of the line, in review vision, I can't see any blankspaces!!
Need to fix it.
Also, it can not change the size of the front.
And please add this feature.
thanks

**Comment by funilrys** [comment]
Hello @driftingdream ,
Please report to https://github.com/Laverna/laverna/issues/971#issuecomment-411423965 which explain the state of this project.

For the future of Laverna, please report to https://github.com/daed/laverna .

Have a nice day/night,
Cheers,
Nissar

**Comment by funilrys** [comment]
@driftingdream Correction, please report to https://github.com/encryptic-team/encryptic for the future of this project :+1:
