### ISSUE TITLE
Android app doesn't request Storage permission

### ISSUE THREAD

**Issue by ghost** [Laverna/laverna#972]
Actions to reproduce:
- Start the configuration of Laverna
- On the "Download your settings or continue" screen, press on Download

What's the issue?
- Because the app hasn't asked for storage permission, it can't download without approving manually the permission (going to app's info > permissions > enable storage)

**Comment by funilrys** [comment]
Hi @reneantoniotg,

please report to https://github.com/Laverna/laverna/issues/971#issuecomment-411423965 .

Have a nice day/night.
