### ISSUE TITLE
Characters are overlaid with fcitx candiate window in desktop version

### ISSUE THREAD

**Issue by hunterforcode** [Laverna/laverna#984]
I am using Ubuntu 18.04 64Bit and fcitx package from the Ubuntu official repository. 
The desktop version I get is 0.7.51, of which comes from your release page [here](https://github.com/Laverna/laverna/releases).

Generally speaking, the candidate window should follow the cursor in the appropriate position, which is illustrated by the following gif picture taken from web version in the Google Chrome browser. 
![illustration 1](https://i.imgur.com/FQx2ocD.gif)

Judging from the gif, we can draw a conclusion that the candidate window is supposed to be below the Chinese characters, however, the desktop version of laverna is NOT the same as the web version.
Here is the desktop version one. 
![illustration 2](https://i.imgur.com/Q3ruJWv.gif)

As you can see, it's strange that Chinese characters are overlaid with the candidate window.

**Comment by funilrys** [comment]
Hi @hunterforcode,

Unfortunately this issue will never be fixed here.

Please report to https://github.com/Laverna/laverna/issues/971#issuecomment-411423965 for the current state of this project and https://github.com/encryptic-team/encryptic for the future of this project.

Have a nice day/night.

Cheers,
Nissar

**Comment by hunterforcode** [comment]
Thanks for your reminding. 
https://github.com/encryptic-team/encryptic 
I try the new project and it resolves my problem.
